/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post95, git sha1 a1bb0255d) */

module sphn_vga_top(o_g, o_b, o_hsync, o_vsync, i_move_up, i_move_down, i_player_two_up, i_player_two_down, i_player_two_active, pix_clk, pix_rst, o_r);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire \$1 ;
  wire \$10 ;
  wire [10:0] \$101 ;
  wire \$103 ;
  wire \$105 ;
  wire \$107 ;
  wire \$109 ;
  wire \$111 ;
  wire \$113 ;
  wire [3:0] \$115 ;
  wire [3:0] \$116 ;
  wire \$118 ;
  wire \$12 ;
  wire [3:0] \$120 ;
  wire [3:0] \$121 ;
  wire \$123 ;
  wire \$125 ;
  wire \$127 ;
  wire \$129 ;
  wire \$131 ;
  wire \$133 ;
  wire [10:0] \$135 ;
  wire [10:0] \$137 ;
  wire \$139 ;
  wire \$14 ;
  wire [10:0] \$141 ;
  wire \$143 ;
  wire \$145 ;
  wire \$147 ;
  wire \$149 ;
  wire [10:0] \$151 ;
  wire [10:0] \$153 ;
  wire \$155 ;
  wire [10:0] \$157 ;
  wire \$159 ;
  wire \$16 ;
  wire \$161 ;
  wire \$163 ;
  wire \$165 ;
  wire \$167 ;
  wire \$169 ;
  wire [10:0] \$171 ;
  wire [10:0] \$173 ;
  wire \$175 ;
  wire [10:0] \$177 ;
  wire \$179 ;
  wire \$18 ;
  wire \$181 ;
  wire \$183 ;
  wire \$185 ;
  wire \$187 ;
  wire \$189 ;
  wire \$191 ;
  wire \$193 ;
  wire \$195 ;
  wire \$197 ;
  wire \$199 ;
  wire [10:0] \$20 ;
  wire \$201 ;
  wire [10:0] \$203 ;
  wire [10:0] \$204 ;
  wire \$206 ;
  wire \$208 ;
  wire [10:0] \$21 ;
  wire [10:0] \$210 ;
  wire [10:0] \$211 ;
  wire \$213 ;
  wire \$215 ;
  wire \$217 ;
  wire \$219 ;
  wire \$221 ;
  wire [11:0] \$223 ;
  wire [10:0] \$225 ;
  wire [11:0] \$227 ;
  wire \$229 ;
  wire [10:0] \$23 ;
  wire \$231 ;
  wire \$233 ;
  wire \$235 ;
  wire \$237 ;
  wire [10:0] \$239 ;
  wire [10:0] \$24 ;
  wire [10:0] \$240 ;
  wire [11:0] \$242 ;
  wire [10:0] \$244 ;
  wire [11:0] \$246 ;
  wire \$248 ;
  wire \$250 ;
  wire \$252 ;
  wire \$254 ;
  wire \$256 ;
  wire [10:0] \$258 ;
  wire [10:0] \$259 ;
  wire [11:0] \$26 ;
  wire \$261 ;
  wire \$263 ;
  wire \$265 ;
  wire [10:0] \$267 ;
  wire [10:0] \$268 ;
  wire [10:0] \$27 ;
  wire \$270 ;
  wire \$272 ;
  wire \$274 ;
  wire [10:0] \$276 ;
  wire [10:0] \$277 ;
  wire \$279 ;
  wire \$281 ;
  wire \$283 ;
  wire \$285 ;
  wire \$287 ;
  wire \$289 ;
  wire [10:0] \$29 ;
  wire [3:0] \$291 ;
  wire [3:0] \$292 ;
  wire \$294 ;
  wire \$296 ;
  wire \$298 ;
  wire \$3 ;
  wire [4:0] \$30 ;
  wire \$300 ;
  wire [3:0] \$302 ;
  wire [3:0] \$303 ;
  wire [11:0] \$33 ;
  wire \$35 ;
  wire \$37 ;
  wire \$39 ;
  wire \$41 ;
  wire \$43 ;
  wire \$45 ;
  wire [3:0] \$47 ;
  wire [3:0] \$48 ;
  wire \$5 ;
  wire [3:0] \$50 ;
  wire [3:0] \$52 ;
  wire \$53 ;
  wire \$56 ;
  wire [3:0] \$58 ;
  wire [3:0] \$59 ;
  wire [3:0] \$61 ;
  wire [3:0] \$63 ;
  wire \$64 ;
  wire \$67 ;
  wire [10:0] \$69 ;
  wire [8:0] \$7 ;
  wire [10:0] \$71 ;
  wire \$73 ;
  wire [10:0] \$75 ;
  wire \$77 ;
  wire \$79 ;
  wire [8:0] \$8 ;
  wire \$81 ;
  wire \$83 ;
  wire [3:0] \$85 ;
  wire [3:0] \$86 ;
  wire \$88 ;
  wire [3:0] \$90 ;
  wire [3:0] \$91 ;
  wire \$93 ;
  wire [10:0] \$95 ;
  wire [10:0] \$97 ;
  wire \$99 ;
  reg [9:0] enemy_paddle_location = 10'h0a5;
  reg [9:0] \enemy_paddle_location$next ;
  reg [2:0] enemy_score = 3'h0;
  reg [2:0] \enemy_score$next ;
  input i_move_down;
  wire i_move_down;
  input i_move_up;
  wire i_move_up;
  input i_player_two_active;
  wire i_player_two_active;
  input i_player_two_down;
  wire i_player_two_down;
  input i_player_two_up;
  wire i_player_two_up;
  output [2:0] o_b;
  wire [2:0] o_b;
  output [2:0] o_g;
  wire [2:0] o_g;
  output o_hsync;
  wire o_hsync;
  output [2:0] o_r;
  wire [2:0] o_r;
  output o_vsync;
  wire o_vsync;
  reg [9:0] paddle_location = 10'h0a5;
  reg [9:0] \paddle_location$next ;
  input pix_clk;
  wire pix_clk;
  input pix_rst;
  wire pix_rst;
  reg [2:0] player_score = 3'h0;
  reg [2:0] \player_score$next ;
  reg pope_h_velocity = 1'h0;
  reg \pope_h_velocity$next ;
  reg [19:0] pope_location = 20'h4b0df;
  reg [19:0] \pope_location$next ;
  reg [2:0] pope_v_velocity = 3'h7;
  reg [2:0] \pope_v_velocity$next ;
  reg prev_vsync = 1'h0;
  reg \prev_vsync$next ;
  reg [7:0] time_until_start = 8'hb3;
  reg [7:0] \time_until_start$next ;
  wire vga_i_enable;
  wire [9:0] vga_i_enemy_paddle_location;
  wire [2:0] vga_i_enemy_score;
  wire [9:0] vga_i_paddle_location;
  wire [2:0] vga_i_player_score;
  wire [19:0] vga_i_pope_location;
  wire [2:0] vga_o_b;
  wire [2:0] vga_o_g;
  wire vga_o_hsync;
  wire [2:0] vga_o_r;
  wire vga_o_vsync;
  assign \$99  = $signed(\$95 ) > $signed(\$97 );
  assign \$101  = enemy_paddle_location + 8'h96;
  assign \$103  = pope_location[19:10] <= \$101 ;
  assign \$105  = \$99  & \$103 ;
  assign \$107  = \$93  & \$105 ;
  assign \$10  = pope_location[9:0] <= 3'h6;
  assign \$111  = \$107  & \$109 ;
  assign \$113  = $signed(pope_v_velocity) > $signed(3'h5);
  assign \$116  = $signed(pope_v_velocity) - $signed(3'h1);
  assign \$118  = $signed(pope_v_velocity) < $signed(3'h3);
  assign \$121  = $signed(pope_v_velocity) + $signed(3'h1);
  assign \$123  = pope_location[9:0] <= 3'h6;
  assign \$125  = pope_location[9:0] >= 10'h25e;
  assign \$127  = ~ vga_o_vsync;
  assign \$12  = pope_location[9:0] >= 10'h25e;
  assign \$129  = prev_vsync & \$127 ;
  assign \$131  = time_until_start > 1'h0;
  assign \$133  = pope_location[9:0] < 6'h32;
  assign \$135  = + pope_location[19:10];
  assign \$137  = paddle_location - 6'h28;
  assign \$139  = $signed(\$135 ) > $signed(\$137 );
  assign \$141  = paddle_location + 8'h96;
  assign \$143  = pope_location[19:10] <= \$141 ;
  assign \$145  = \$139  & \$143 ;
  assign \$147  = \$133  & \$145 ;
  assign \$14  = ~ vga_o_vsync;
  assign \$149  = pope_location[9:0] >= 10'h22c;
  assign \$151  = + pope_location[19:10];
  assign \$153  = enemy_paddle_location - 6'h28;
  assign \$155  = $signed(\$151 ) > $signed(\$153 );
  assign \$157  = enemy_paddle_location + 8'h96;
  assign \$159  = pope_location[19:10] <= \$157 ;
  assign \$161  = \$155  & \$159 ;
  assign \$163  = \$149  & \$161 ;
  assign \$165  = ~ i_player_two_active;
  assign \$167  = \$163  & \$165 ;
  assign \$16  = prev_vsync & \$14 ;
  assign \$169  = pope_location[9:0] >= 10'h22c;
  assign \$171  = + pope_location[19:10];
  assign \$173  = enemy_paddle_location - 6'h28;
  assign \$175  = $signed(\$171 ) > $signed(\$173 );
  assign \$177  = enemy_paddle_location + 8'h96;
  assign \$179  = pope_location[19:10] <= \$177 ;
  assign \$181  = \$175  & \$179 ;
  assign \$183  = \$169  & \$181 ;
  assign \$187  = \$183  & \$185 ;
  assign \$18  = time_until_start > 1'h0;
  assign \$189  = pope_location[9:0] <= 3'h6;
  assign \$191  = pope_location[9:0] >= 10'h25e;
  assign \$193  = ~ vga_o_vsync;
  assign \$195  = prev_vsync & \$193 ;
  assign \$197  = time_until_start > 1'h0;
  assign \$1  = ~ vga_o_vsync;
  assign \$199  = paddle_location >= 2'h3;
  assign \$201  = i_move_up & \$199 ;
  assign \$204  = paddle_location - 2'h3;
  assign \$206  = paddle_location < 9'h147;
  assign \$208  = i_move_down & \$206 ;
  assign \$211  = paddle_location + 2'h3;
  assign \$213  = pope_location[9:0] <= 3'h6;
  assign \$215  = pope_location[9:0] >= 10'h25e;
  assign \$217  = ~ vga_o_vsync;
  assign \$21  = pope_location[9:0] + 2'h3;
  assign \$219  = prev_vsync & \$217 ;
  assign \$221  = time_until_start > 1'h0;
  assign \$223  = + pope_location[19:10];
  assign \$225  = enemy_paddle_location + 7'h4b;
  assign \$227  = \$225  - 5'h14;
  assign \$229  = $signed(\$223 ) > $signed(\$227 );
  assign \$231  = enemy_paddle_location < 9'h136;
  assign \$233  = \$229  & \$231 ;
  assign \$235  = ~ i_player_two_active;
  assign \$237  = \$233  & \$235 ;
  assign \$240  = enemy_paddle_location + 2'h2;
  assign \$242  = + pope_location[19:10];
  assign \$244  = enemy_paddle_location + 7'h4b;
  assign \$246  = \$244  - 5'h14;
  assign \$248  = $signed(\$242 ) < $signed(\$246 );
  assign \$24  = pope_location[9:0] - 2'h3;
  assign \$250  = enemy_paddle_location > 5'h14;
  assign \$252  = \$248  & \$250 ;
  assign \$254  = ~ i_player_two_active;
  assign \$256  = \$252  & \$254 ;
  assign \$259  = enemy_paddle_location - 2'h2;
  assign \$261  = enemy_paddle_location >= 2'h3;
  assign \$263  = i_player_two_up & \$261 ;
  assign \$265  = \$263  & i_player_two_active;
  assign \$268  = enemy_paddle_location - 2'h3;
  assign \$270  = enemy_paddle_location < 9'h147;
  assign \$272  = i_player_two_down & \$270 ;
  assign \$274  = \$272  & i_player_two_active;
  assign \$277  = enemy_paddle_location + 2'h3;
  assign \$27  = + pope_location[19:10];
  assign \$279  = pope_location[9:0] <= 3'h6;
  assign \$281  = pope_location[9:0] >= 10'h25e;
  assign \$283  = ~ vga_o_vsync;
  assign \$285  = prev_vsync & \$283 ;
  assign \$287  = time_until_start > 1'h0;
  assign \$289  = pope_location[9:0] <= 3'h6;
  assign \$292  = enemy_score + 1'h1;
  assign \$294  = ~ vga_o_vsync;
  assign \$296  = prev_vsync & \$294 ;
  assign \$298  = time_until_start > 1'h0;
  assign \$300  = pope_location[9:0] >= 10'h25e;
  assign \$303  = player_score + 1'h1;
  always @(posedge pix_clk)
    prev_vsync <= \prev_vsync$next ;
  always @(posedge pix_clk)
    time_until_start <= \time_until_start$next ;
  always @(posedge pix_clk)
    pope_location <= \pope_location$next ;
  always @(posedge pix_clk)
    pope_v_velocity <= \pope_v_velocity$next ;
  always @(posedge pix_clk)
    pope_h_velocity <= \pope_h_velocity$next ;
  assign \$30  = $signed(3'h3) * $signed(pope_v_velocity);
  always @(posedge pix_clk)
    paddle_location <= \paddle_location$next ;
  always @(posedge pix_clk)
    enemy_paddle_location <= \enemy_paddle_location$next ;
  always @(posedge pix_clk)
    enemy_score <= \enemy_score$next ;
  always @(posedge pix_clk)
    player_score <= \player_score$next ;
  assign \$29  = + $signed(\$30 );
  assign \$33  = $signed(\$27 ) + $signed(\$29 );
  assign \$35  = pope_location[9:0] <= 3'h6;
  assign \$37  = pope_location[9:0] >= 10'h25e;
  assign \$3  = prev_vsync & \$1 ;
  assign \$39  = ~ vga_o_vsync;
  assign \$41  = prev_vsync & \$39 ;
  assign \$43  = time_until_start > 1'h0;
  assign \$45  = pope_location[19:10] <= 5'h14;
  assign \$48  = + $signed(pope_v_velocity);
  assign \$50  = - $signed(pope_v_velocity);
  assign \$53  = $signed(pope_v_velocity) > $signed(3'h0);
  assign \$52  = \$53  ? \$48  : \$50 ;
  assign \$56  = pope_location[19:10] >= 9'h1b8;
  assign \$5  = time_until_start > 1'h0;
  assign \$59  = + $signed(pope_v_velocity);
  assign \$61  = - $signed(pope_v_velocity);
  assign \$64  = $signed(pope_v_velocity) < $signed(3'h0);
  assign \$63  = \$64  ? \$59  : \$61 ;
  assign \$67  = pope_location[9:0] < 6'h32;
  assign \$69  = + pope_location[19:10];
  assign \$71  = paddle_location - 6'h28;
  assign \$73  = $signed(\$69 ) > $signed(\$71 );
  assign \$75  = paddle_location + 8'h96;
  assign \$77  = pope_location[19:10] <= \$75 ;
  assign \$79  = \$73  & \$77 ;
  assign \$81  = \$67  & \$79 ;
  assign \$83  = $signed(pope_v_velocity) > $signed(3'h5);
  assign \$86  = $signed(pope_v_velocity) - $signed(3'h1);
  assign \$88  = $signed(pope_v_velocity) < $signed(3'h3);
  assign \$8  = time_until_start - 1'h1;
  assign \$91  = $signed(pope_v_velocity) + $signed(3'h1);
  assign \$93  = pope_location[9:0] >= 10'h22c;
  assign \$95  = + pope_location[19:10];
  assign \$97  = enemy_paddle_location - 6'h28;
  \sphn_vga_top.vga  vga (
    .i_enable(1'h1),
    .i_enemy_paddle_location(vga_i_enemy_paddle_location),
    .i_enemy_score(vga_i_enemy_score),
    .i_paddle_location(vga_i_paddle_location),
    .i_player_score(vga_i_player_score),
    .i_pope_location(vga_i_pope_location),
    .o_b(vga_o_b),
    .o_g(vga_o_g),
    .o_hsync(vga_o_hsync),
    .o_r(vga_o_r),
    .o_vsync(vga_o_vsync),
    .pix_clk(pix_clk),
    .pix_rst(pix_rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \prev_vsync$next  = vga_o_vsync;
    if (pix_rst) begin
      \prev_vsync$next  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \time_until_start$next  = time_until_start;
    if (\$3 ) begin
      (* full_case = 32'd1 *)
      if (\$5 ) begin
        \time_until_start$next  = \$8 [7:0];
      end else begin
        if (\$10 ) begin
          \time_until_start$next  = 8'hb3;
        end
        if (\$12 ) begin
          \time_until_start$next  = 8'hb3;
        end
      end
    end
    if (pix_rst) begin
      \time_until_start$next  = 8'hb3;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \pope_location$next  = pope_location;
    if (\$16 ) begin
      (* full_case = 32'd1 *)
      if (\$18 ) begin
      end else begin
        (* full_case = 32'd1 *)
        if (pope_h_velocity) begin
          \pope_location$next [9:0] = \$21 [9:0];
        end else begin
          \pope_location$next [9:0] = \$24 [9:0];
        end
        begin
            \pope_location$next [19:10] = \$33 [9:0];
        end
        if (\$35 ) begin
          \pope_location$next  = 20'h4b0df;
        end
        if (\$37 ) begin
          \pope_location$next  = 20'h4b0df;
        end
      end
    end
    if (pix_rst) begin
      \pope_location$next  = 20'h4b0df;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \pope_v_velocity$next  = pope_v_velocity;
    if (\$41 ) begin
      (* full_case = 32'd1 *)
      if (\$43 ) begin
      end else begin
        if (\$45 ) begin
          \pope_v_velocity$next  = \$52 [2:0];
        end
        if (\$56 ) begin
          \pope_v_velocity$next  = \$63 [2:0];
        end
        if (\$81 ) begin
          if (i_move_up) begin
            if (\$83 ) begin
              \pope_v_velocity$next  = \$86 [2:0];
            end
          end
          if (i_move_down) begin
            if (\$88 ) begin
              \pope_v_velocity$next  = \$91 [2:0];
            end
          end
        end
        if (\$111 ) begin
          if (i_player_two_up) begin
            if (\$113 ) begin
              \pope_v_velocity$next  = \$116 [2:0];
            end
          end
          if (i_player_two_down) begin
            if (\$118 ) begin
              \pope_v_velocity$next  = \$121 [2:0];
            end
          end
        end
        if (\$123 ) begin
          \pope_v_velocity$next  = 3'h7;
        end
        if (\$125 ) begin
          \pope_v_velocity$next  = 3'h7;
        end
      end
    end
    if (pix_rst) begin
      \pope_v_velocity$next  = 3'h7;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \pope_h_velocity$next  = pope_h_velocity;
    if (\$129 ) begin
      (* full_case = 32'd1 *)
      if (\$131 ) begin
      end else begin
        if (\$147 ) begin
          \pope_h_velocity$next  = 1'h1;
        end
        if (\$167 ) begin
          \pope_h_velocity$next  = 1'h0;
        end
        if (\$187 ) begin
          \pope_h_velocity$next  = 1'h0;
        end
        if (\$189 ) begin
          \pope_h_velocity$next  = 1'h0;
        end
        if (\$191 ) begin
          \pope_h_velocity$next  = 1'h0;
        end
      end
    end
    if (pix_rst) begin
      \pope_h_velocity$next  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \paddle_location$next  = paddle_location;
    if (\$195 ) begin
      (* full_case = 32'd1 *)
      if (\$197 ) begin
      end else begin
        if (\$201 ) begin
          \paddle_location$next  = \$204 [9:0];
        end
        if (\$208 ) begin
          \paddle_location$next  = \$211 [9:0];
        end
        if (\$213 ) begin
          \paddle_location$next  = 10'h0a5;
        end
        if (\$215 ) begin
          \paddle_location$next  = 10'h0a5;
        end
      end
    end
    if (pix_rst) begin
      \paddle_location$next  = 10'h0a5;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \enemy_paddle_location$next  = enemy_paddle_location;
    if (\$219 ) begin
      (* full_case = 32'd1 *)
      if (\$221 ) begin
      end else begin
        if (\$237 ) begin
          \enemy_paddle_location$next  = \$240 [9:0];
        end
        if (\$256 ) begin
          \enemy_paddle_location$next  = \$259 [9:0];
        end
        if (\$265 ) begin
          \enemy_paddle_location$next  = \$268 [9:0];
        end
        if (\$274 ) begin
          \enemy_paddle_location$next  = \$277 [9:0];
        end
        if (\$279 ) begin
          \enemy_paddle_location$next  = 10'h0a5;
        end
        if (\$281 ) begin
          \enemy_paddle_location$next  = 10'h0a5;
        end
      end
    end
    if (pix_rst) begin
      \enemy_paddle_location$next  = 10'h0a5;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \enemy_score$next  = enemy_score;
    if (\$285 ) begin
      (* full_case = 32'd1 *)
      if (\$287 ) begin
      end else begin
        if (\$289 ) begin
          \enemy_score$next  = \$292 [2:0];
        end
      end
    end
    if (pix_rst) begin
      \enemy_score$next  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \player_score$next  = player_score;
    if (\$296 ) begin
      (* full_case = 32'd1 *)
      if (\$298 ) begin
      end else begin
        if (\$300 ) begin
          \player_score$next  = \$303 [2:0];
        end
      end
    end
    if (pix_rst) begin
      \player_score$next  = 3'h0;
    end
  end
  assign \$7  = \$8 ;
  assign \$20  = \$21 ;
  assign \$23  = \$24 ;
  assign \$26  = \$33 ;
  assign \$47  = \$52 ;
  assign \$58  = \$63 ;
  assign \$85  = \$86 ;
  assign \$90  = \$91 ;
  assign \$115  = \$116 ;
  assign \$120  = \$121 ;
  assign \$203  = \$204 ;
  assign \$210  = \$211 ;
  assign \$239  = \$240 ;
  assign \$258  = \$259 ;
  assign \$267  = \$268 ;
  assign \$276  = \$277 ;
  assign \$291  = \$292 ;
  assign \$302  = \$303 ;
  assign o_vsync = vga_o_vsync;
  assign o_hsync = vga_o_hsync;
  assign o_b = vga_o_b;
  assign o_g = vga_o_g;
  assign o_r = vga_o_r;
  assign vga_i_enemy_score = enemy_score;
  assign vga_i_player_score = player_score;
  assign vga_i_enemy_paddle_location = enemy_paddle_location;
  assign vga_i_paddle_location = paddle_location;
  assign vga_i_pope_location = pope_location;
  assign vga_i_enable = 1'h1;
  assign \$109  = i_player_two_active;
  assign \$185  = i_player_two_active;
endmodule

module \sphn_vga_top.vga (o_vsync, i_pope_location, i_paddle_location, i_enemy_paddle_location, i_player_score, i_enemy_score, o_r, o_g, o_b, o_hsync, pix_rst, pix_clk, i_enable);
  reg \$auto$verilog_backend.cc:2352:dump_module$2  = 0;
  wire [11:0] \$1 ;
  wire \$101 ;
  wire [2:0] \$103 ;
  wire \$105 ;
  wire \$107 ;
  wire \$109 ;
  wire \$11 ;
  wire \$111 ;
  wire \$113 ;
  wire \$115 ;
  wire \$117 ;
  wire [2:0] \$119 ;
  wire \$121 ;
  wire [10:0] \$123 ;
  wire \$125 ;
  wire \$127 ;
  wire \$129 ;
  wire \$13 ;
  wire \$131 ;
  wire \$133 ;
  wire \$135 ;
  wire \$137 ;
  wire [10:0] \$139 ;
  wire \$141 ;
  wire \$143 ;
  wire \$145 ;
  wire \$147 ;
  wire \$149 ;
  wire \$15 ;
  wire \$151 ;
  wire \$153 ;
  wire \$155 ;
  wire \$157 ;
  wire \$159 ;
  wire \$161 ;
  wire \$163 ;
  wire \$165 ;
  wire \$167 ;
  wire \$169 ;
  wire \$17 ;
  wire \$171 ;
  wire [2:0] \$173 ;
  wire \$175 ;
  wire \$177 ;
  wire \$179 ;
  wire \$181 ;
  wire \$183 ;
  wire \$185 ;
  wire \$187 ;
  wire [2:0] \$189 ;
  wire \$19 ;
  wire \$191 ;
  wire [10:0] \$193 ;
  wire \$195 ;
  wire \$197 ;
  wire \$199 ;
  wire [11:0] \$2 ;
  wire \$201 ;
  wire \$203 ;
  wire \$205 ;
  wire \$207 ;
  wire [10:0] \$209 ;
  wire \$21 ;
  wire \$211 ;
  wire \$213 ;
  wire \$215 ;
  wire \$217 ;
  wire \$219 ;
  wire \$221 ;
  wire \$223 ;
  wire \$225 ;
  wire \$227 ;
  wire [11:0] \$229 ;
  wire \$23 ;
  wire [11:0] \$231 ;
  wire [11:0] \$233 ;
  wire [11:0] \$235 ;
  wire [11:0] \$237 ;
  wire [11:0] \$239 ;
  wire [11:0] \$241 ;
  wire [11:0] \$243 ;
  wire [11:0] \$245 ;
  wire [11:0] \$247 ;
  wire [11:0] \$249 ;
  wire \$25 ;
  wire [11:0] \$251 ;
  wire [11:0] \$253 ;
  wire [11:0] \$255 ;
  wire [11:0] \$257 ;
  wire [11:0] \$259 ;
  wire [11:0] \$261 ;
  wire [11:0] \$263 ;
  wire [11:0] \$265 ;
  wire [11:0] \$267 ;
  wire [11:0] \$269 ;
  wire \$27 ;
  wire [11:0] \$271 ;
  wire [11:0] \$273 ;
  wire [11:0] \$275 ;
  wire [11:0] \$277 ;
  wire [11:0] \$279 ;
  wire [11:0] \$281 ;
  wire [11:0] \$283 ;
  wire [11:0] \$285 ;
  wire [11:0] \$287 ;
  wire [11:0] \$289 ;
  wire \$29 ;
  wire [11:0] \$291 ;
  wire [11:0] \$293 ;
  wire [11:0] \$295 ;
  wire \$31 ;
  wire \$33 ;
  wire \$35 ;
  wire \$37 ;
  wire \$39 ;
  wire \$4 ;
  wire \$41 ;
  wire \$43 ;
  wire \$45 ;
  wire \$47 ;
  wire \$49 ;
  wire \$51 ;
  wire [10:0] \$53 ;
  wire \$55 ;
  wire \$57 ;
  wire \$59 ;
  wire [11:0] \$6 ;
  wire \$61 ;
  wire \$63 ;
  wire \$65 ;
  wire \$67 ;
  wire [10:0] \$69 ;
  wire [11:0] \$7 ;
  wire \$71 ;
  wire \$73 ;
  wire \$75 ;
  wire \$77 ;
  wire \$79 ;
  wire \$81 ;
  wire \$83 ;
  wire \$85 ;
  wire \$87 ;
  wire \$89 ;
  wire \$9 ;
  wire \$91 ;
  wire \$93 ;
  wire \$95 ;
  wire \$97 ;
  wire \$99 ;
  reg [21:0] clock = 22'h000000;
  reg [21:0] \clock$next ;
  input i_enable;
  wire i_enable;
  input [9:0] i_enemy_paddle_location;
  wire [9:0] i_enemy_paddle_location;
  input [2:0] i_enemy_score;
  wire [2:0] i_enemy_score;
  input [9:0] i_paddle_location;
  wire [9:0] i_paddle_location;
  input [2:0] i_player_score;
  wire [2:0] i_player_score;
  input [19:0] i_pope_location;
  wire [19:0] i_pope_location;
  output [2:0] o_b;
  reg [2:0] o_b;
  output [2:0] o_g;
  reg [2:0] o_g;
  output o_hsync;
  reg o_hsync;
  output [2:0] o_r;
  reg [2:0] o_r;
  output o_vsync;
  reg o_vsync;
  reg [4:0] palette_index;
  input pix_clk;
  wire pix_clk;
  input pix_rst;
  wire pix_rst;
  assign \$9  = clock[21:11] == 10'h20c;
  assign \$99  = clock[21:11] < 7'h4b;
  assign \$101  = \$97  & \$99 ;
  assign \$103  = ~ i_player_score;
  assign \$105  = clock[10:0] >= 10'h203;
  assign \$107  = clock[10:0] < 10'h21c;
  assign \$109  = \$105  & \$107 ;
  assign \$111  = clock[21:11] >= 6'h32;
  assign \$113  = \$109  & \$111 ;
  assign \$115  = clock[21:11] < 7'h4b;
  assign \$117  = \$113  & \$115 ;
  assign \$11  = clock[10:0] >= 10'h290;
  assign \$119  = ~ i_enemy_score;
  assign \$121  = clock[21:11] >= i_paddle_location;
  assign \$123  = i_paddle_location + 8'h96;
  assign \$125  = clock[21:11] < \$123 ;
  assign \$127  = \$121  & \$125 ;
  assign \$129  = clock[10:0] >= 5'h19;
  assign \$131  = \$127  & \$129 ;
  assign \$133  = clock[10:0] < 6'h32;
  assign \$135  = \$131  & \$133 ;
  assign \$137  = clock[21:11] >= i_enemy_paddle_location;
  assign \$13  = clock[10:0] < 10'h2f0;
  assign \$139  = i_enemy_paddle_location + 8'h96;
  assign \$141  = clock[21:11] < \$139 ;
  assign \$143  = \$137  & \$141 ;
  assign \$145  = clock[10:0] < 10'h267;
  assign \$147  = \$143  & \$145 ;
  assign \$149  = clock[10:0] >= 10'h24e;
  assign \$151  = \$147  & \$149 ;
  assign \$153  = clock[10:0] >= 10'h280;
  assign \$155  = clock[21:11] >= 9'h1e0;
  assign \$157  = \$153  | \$155 ;
  assign \$15  = \$11  & \$13 ;
  assign \$159  = clock[10:0] >= 7'h64;
  assign \$161  = clock[10:0] < 7'h7d;
  assign \$163  = \$159  & \$161 ;
  assign \$165  = clock[21:11] >= 6'h32;
  assign \$167  = \$163  & \$165 ;
  assign \$169  = clock[21:11] < 7'h4b;
  assign \$171  = \$167  & \$169 ;
  assign \$173  = ~ i_player_score;
  assign \$175  = clock[10:0] >= 10'h203;
  assign \$177  = clock[10:0] < 10'h21c;
  assign \$17  = clock[21:11] >= 9'h1ea;
  assign \$179  = \$175  & \$177 ;
  assign \$181  = clock[21:11] >= 6'h32;
  assign \$183  = \$179  & \$181 ;
  assign \$185  = clock[21:11] < 7'h4b;
  assign \$187  = \$183  & \$185 ;
  assign \$189  = ~ i_enemy_score;
  assign \$191  = clock[21:11] >= i_paddle_location;
  assign \$193  = i_paddle_location + 8'h96;
  assign \$195  = clock[21:11] < \$193 ;
  assign \$197  = \$191  & \$195 ;
  assign \$19  = clock[21:11] < 9'h1ec;
  assign \$199  = clock[10:0] >= 5'h19;
  assign \$201  = \$197  & \$199 ;
  assign \$203  = clock[10:0] < 6'h32;
  assign \$205  = \$201  & \$203 ;
  assign \$207  = clock[21:11] >= i_enemy_paddle_location;
  assign \$209  = i_enemy_paddle_location + 8'h96;
  assign \$211  = clock[21:11] < \$209 ;
  assign \$213  = \$207  & \$211 ;
  assign \$215  = clock[10:0] < 10'h267;
  assign \$217  = \$213  & \$215 ;
  assign \$21  = \$17  & \$19 ;
  assign \$219  = clock[10:0] >= 10'h24e;
  assign \$221  = \$217  & \$219 ;
  assign \$223  = clock[10:0] >= 10'h280;
  assign \$225  = clock[21:11] >= 9'h1e0;
  assign \$227  = \$223  | \$225 ;
  assign \$229  = clock[10:0] - i_pope_location[9:0];
  assign \$231  = clock[21:11] - i_pope_location[19:10];
  assign \$233  = clock[21:11] - i_pope_location[19:10];
  assign \$235  = clock[21:11] - i_pope_location[19:10];
  assign \$237  = clock[21:11] - i_pope_location[19:10];
  assign \$23  = clock[10:0] >= 7'h64;
  assign \$239  = clock[21:11] - i_pope_location[19:10];
  assign \$241  = clock[21:11] - i_pope_location[19:10];
  assign \$243  = clock[21:11] - i_pope_location[19:10];
  assign \$245  = clock[21:11] - i_pope_location[19:10];
  assign \$247  = clock[21:11] - i_pope_location[19:10];
  assign \$249  = clock[21:11] - i_pope_location[19:10];
  assign \$251  = clock[21:11] - i_pope_location[19:10];
  assign \$253  = clock[21:11] - i_pope_location[19:10];
  assign \$255  = clock[21:11] - i_pope_location[19:10];
  assign \$257  = clock[21:11] - i_pope_location[19:10];
  assign \$25  = clock[10:0] < 7'h7d;
  assign \$259  = clock[21:11] - i_pope_location[19:10];
  assign \$261  = clock[21:11] - i_pope_location[19:10];
  assign \$263  = clock[21:11] - i_pope_location[19:10];
  assign \$265  = clock[21:11] - i_pope_location[19:10];
  assign \$267  = clock[21:11] - i_pope_location[19:10];
  assign \$269  = clock[21:11] - i_pope_location[19:10];
  assign \$271  = clock[21:11] - i_pope_location[19:10];
  assign \$273  = clock[21:11] - i_pope_location[19:10];
  assign \$275  = clock[21:11] - i_pope_location[19:10];
  assign \$277  = clock[21:11] - i_pope_location[19:10];
  assign \$27  = \$23  & \$25 ;
  assign \$279  = clock[21:11] - i_pope_location[19:10];
  assign \$281  = clock[21:11] - i_pope_location[19:10];
  assign \$283  = clock[21:11] - i_pope_location[19:10];
  assign \$285  = clock[21:11] - i_pope_location[19:10];
  assign \$287  = clock[21:11] - i_pope_location[19:10];
  assign \$289  = clock[21:11] - i_pope_location[19:10];
  assign \$291  = clock[21:11] - i_pope_location[19:10];
  assign \$293  = clock[21:11] - i_pope_location[19:10];
  assign \$295  = clock[21:11] - i_pope_location[19:10];
  always @(posedge pix_clk)
    clock <= \clock$next ;
  assign \$2  = clock[10:0] + 1'h1;
  assign \$29  = clock[21:11] >= 6'h32;
  assign \$31  = \$27  & \$29 ;
  assign \$33  = clock[21:11] < 7'h4b;
  assign \$35  = \$31  & \$33 ;
  assign \$37  = clock[10:0] >= 10'h203;
  assign \$39  = clock[10:0] < 10'h21c;
  assign \$41  = \$37  & \$39 ;
  assign \$43  = clock[21:11] >= 6'h32;
  assign \$45  = \$41  & \$43 ;
  assign \$47  = clock[21:11] < 7'h4b;
  assign \$4  = clock[10:0] == 10'h31f;
  assign \$49  = \$45  & \$47 ;
  assign \$51  = clock[21:11] >= i_paddle_location;
  assign \$53  = i_paddle_location + 8'h96;
  assign \$55  = clock[21:11] < \$53 ;
  assign \$57  = \$51  & \$55 ;
  assign \$59  = clock[10:0] >= 5'h19;
  assign \$61  = \$57  & \$59 ;
  assign \$63  = clock[10:0] < 6'h32;
  assign \$65  = \$61  & \$63 ;
  assign \$67  = clock[21:11] >= i_enemy_paddle_location;
  assign \$69  = i_enemy_paddle_location + 8'h96;
  assign \$71  = clock[21:11] < \$69 ;
  assign \$73  = \$67  & \$71 ;
  assign \$75  = clock[10:0] < 10'h267;
  assign \$77  = \$73  & \$75 ;
  assign \$7  = clock[21:11] + 1'h1;
  assign \$79  = clock[10:0] >= 10'h24e;
  assign \$81  = \$77  & \$79 ;
  assign \$83  = clock[10:0] >= 10'h280;
  assign \$85  = clock[21:11] >= 9'h1e0;
  assign \$87  = \$83  | \$85 ;
  assign \$89  = clock[10:0] >= 7'h64;
  assign \$91  = clock[10:0] < 7'h7d;
  assign \$93  = \$89  & \$91 ;
  assign \$95  = clock[21:11] >= 6'h32;
  assign \$97  = \$93  & \$95 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \clock$next  = clock;
    if (i_enable) begin
      \clock$next [10:0] = \$2 [10:0];
    end
    if (\$4 ) begin
      \clock$next [10:0] = 11'h000;
      \clock$next [21:11] = \$7 [10:0];
      if (\$9 ) begin
        \clock$next [21:11] = 11'h000;
      end
    end
    if (pix_rst) begin
      \clock$next  = 22'h000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_hsync = 1'h1;
    if (\$15 ) begin
      o_hsync = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_vsync = 1'h1;
    if (\$21 ) begin
      o_vsync = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_r = 3'h0;
    if (\$35 ) begin
      o_r = 3'h7;
    end
    if (\$49 ) begin
      o_r = 3'h7;
    end
    casez (palette_index)
      5'h01:
          o_r = 3'h2;
      5'h02:
          o_r = 3'h3;
      5'h03:
          o_r = 3'h2;
      5'h04:
          o_r = 3'h3;
      5'h05:
          o_r = 3'h4;
      5'h06:
          o_r = 3'h4;
      5'h07:
          o_r = 3'h4;
      5'h08:
          o_r = 3'h4;
      5'h09:
          o_r = 3'h5;
      5'h0a:
          o_r = 3'h6;
      5'h0b:
          o_r = 3'h4;
      5'h0c:
          o_r = 3'h5;
      5'h0d:
          o_r = 3'h4;
      5'h0e:
          o_r = 3'h5;
      5'h0f:
          o_r = 3'h6;
      5'h10:
          o_r = 3'h6;
      5'h11:
          o_r = 3'h6;
      5'h12:
          o_r = 3'h7;
      5'h13:
          o_r = 3'h7;
      5'h14:
          o_r = 3'h5;
      5'h15:
          o_r = 3'h6;
      5'h16:
          o_r = 3'h6;
      5'h17:
          o_r = 3'h7;
      5'h18:
          o_r = 3'h7;
      5'h19:
          o_r = 3'h7;
      5'h1a:
          o_r = 3'h7;
      5'h1b:
          o_r = 3'h7;
      5'h1c:
          o_r = 3'h5;
      5'h1d:
          o_r = 3'h7;
      5'h1e:
          o_r = 3'h7;
    endcase
    if (\$65 ) begin
      o_r = 3'h7;
    end
    if (\$81 ) begin
      o_r = 3'h7;
    end
    if (\$87 ) begin
      o_r = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_b = 3'h0;
    if (\$101 ) begin
      o_b = \$103 ;
    end
    if (\$117 ) begin
      o_b = \$119 ;
    end
    casez (palette_index)
      5'h01:
          o_b = 3'h0;
      5'h02:
          o_b = 3'h0;
      5'h03:
          o_b = 3'h0;
      5'h04:
          o_b = 3'h1;
      5'h05:
          o_b = 3'h0;
      5'h06:
          o_b = 3'h0;
      5'h07:
          o_b = 3'h2;
      5'h08:
          o_b = 3'h3;
      5'h09:
          o_b = 3'h0;
      5'h0a:
          o_b = 3'h0;
      5'h0b:
          o_b = 3'h1;
      5'h0c:
          o_b = 3'h1;
      5'h0d:
          o_b = 3'h4;
      5'h0e:
          o_b = 3'h3;
      5'h0f:
          o_b = 3'h0;
      5'h10:
          o_b = 3'h2;
      5'h11:
          o_b = 3'h4;
      5'h12:
          o_b = 3'h1;
      5'h13:
          o_b = 3'h3;
      5'h14:
          o_b = 3'h3;
      5'h15:
          o_b = 3'h2;
      5'h16:
          o_b = 3'h4;
      5'h17:
          o_b = 3'h1;
      5'h18:
          o_b = 3'h3;
      5'h19:
          o_b = 3'h5;
      5'h1a:
          o_b = 3'h3;
      5'h1b:
          o_b = 3'h5;
      5'h1c:
          o_b = 3'h5;
      5'h1d:
          o_b = 3'h7;
      5'h1e:
          o_b = 3'h5;
    endcase
    if (\$135 ) begin
      o_b = 3'h7;
    end
    if (\$151 ) begin
      o_b = 3'h7;
    end
    if (\$157 ) begin
      o_b = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_g = 3'h0;
    if (\$171 ) begin
      o_g = \$173 ;
    end
    if (\$187 ) begin
      o_g = \$189 ;
    end
    casez (palette_index)
      5'h01:
          o_g = 3'h1;
      5'h02:
          o_g = 3'h0;
      5'h03:
          o_g = 3'h2;
      5'h04:
          o_g = 3'h2;
      5'h05:
          o_g = 3'h2;
      5'h06:
          o_g = 3'h3;
      5'h07:
          o_g = 3'h3;
      5'h08:
          o_g = 3'h3;
      5'h09:
          o_g = 3'h3;
      5'h0a:
          o_g = 3'h3;
      5'h0b:
          o_g = 3'h4;
      5'h0c:
          o_g = 3'h4;
      5'h0d:
          o_g = 3'h4;
      5'h0e:
          o_g = 3'h4;
      5'h0f:
          o_g = 3'h4;
      5'h10:
          o_g = 3'h4;
      5'h11:
          o_g = 3'h4;
      5'h12:
          o_g = 3'h4;
      5'h13:
          o_g = 3'h4;
      5'h14:
          o_g = 3'h5;
      5'h15:
          o_g = 3'h5;
      5'h16:
          o_g = 3'h5;
      5'h17:
          o_g = 3'h5;
      5'h18:
          o_g = 3'h5;
      5'h19:
          o_g = 3'h5;
      5'h1a:
          o_g = 3'h6;
      5'h1b:
          o_g = 3'h6;
      5'h1c:
          o_g = 3'h6;
      5'h1d:
          o_g = 3'h6;
      5'h1e:
          o_g = 3'h7;
    endcase
    if (\$205 ) begin
      o_g = 3'h7;
    end
    if (\$221 ) begin
      o_g = 3'h7;
    end
    if (\$227 ) begin
      o_g = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    palette_index = 5'h00;
    casez (\$229 )
      12'h000:
          casez (\$231 )
            12'h010:
                palette_index = 5'h1e;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h1a;
            12'h014:
                palette_index = 5'h1e;
          endcase
      12'h001:
          casez (\$233 )
            12'h010:
                palette_index = 5'h13;
            12'h011:
                palette_index = 5'h15;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h15;
            12'h014:
                palette_index = 5'h18;
            12'h015:
                palette_index = 5'h1e;
          endcase
      12'h002:
          casez (\$235 )
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h15;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h15;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h18;
            12'h017:
                palette_index = 5'h13;
            12'h018:
                palette_index = 5'h1a;
          endcase
      12'h003:
          casez (\$237 )
            12'h00f:
                palette_index = 5'h0e;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h15;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h15;
            12'h016:
                palette_index = 5'h13;
            12'h017:
                palette_index = 5'h18;
            12'h018:
                palette_index = 5'h13;
            12'h019:
                palette_index = 5'h1e;
          endcase
      12'h004:
          casez (\$239 )
            12'h00a:
                palette_index = 5'h1c;
            12'h00b:
                palette_index = 5'h0d;
            12'h00c:
                palette_index = 5'h0e;
            12'h00d:
                palette_index = 5'h0d;
            12'h00e:
                palette_index = 5'h0b;
            12'h00f:
                palette_index = 5'h07;
            12'h010:
                palette_index = 5'h0e;
            12'h011:
                palette_index = 5'h0e;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h0c;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h12;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h17;
            12'h019:
                palette_index = 5'h18;
          endcase
      12'h005:
          casez (\$241 )
            12'h008:
                palette_index = 5'h1c;
            12'h009:
                palette_index = 5'h07;
            12'h00a:
                palette_index = 5'h08;
            12'h00b:
                palette_index = 5'h07;
            12'h00c:
                palette_index = 5'h07;
            12'h00d:
                palette_index = 5'h07;
            12'h00e:
                palette_index = 5'h07;
            12'h00f:
                palette_index = 5'h0b;
            12'h010:
                palette_index = 5'h0b;
            12'h011:
                palette_index = 5'h0e;
            12'h012:
                palette_index = 5'h0c;
            12'h013:
                palette_index = 5'h0c;
            12'h014:
                palette_index = 5'h09;
            12'h015:
                palette_index = 5'h0a;
            12'h016:
                palette_index = 5'h0a;
            12'h017:
                palette_index = 5'h0a;
            12'h018:
                palette_index = 5'h09;
            12'h019:
                palette_index = 5'h0a;
            12'h01a:
                palette_index = 5'h09;
            12'h01b:
                palette_index = 5'h10;
            12'h01c:
                palette_index = 5'h09;
            12'h01d:
                palette_index = 5'h09;
            12'h01e:
                palette_index = 5'h05;
            12'h01f:
                palette_index = 5'h06;
            12'h020:
                palette_index = 5'h05;
            12'h021:
                palette_index = 5'h0c;
          endcase
      12'h006:
          casez (\$243 )
            12'h007:
                palette_index = 5'h0d;
            12'h008:
                palette_index = 5'h0b;
            12'h009:
                palette_index = 5'h07;
            12'h00a:
                palette_index = 5'h07;
            12'h00b:
                palette_index = 5'h07;
            12'h00c:
                palette_index = 5'h0b;
            12'h00d:
                palette_index = 5'h07;
            12'h00e:
                palette_index = 5'h0c;
            12'h00f:
                palette_index = 5'h0c;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h0c;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h09;
            12'h014:
                palette_index = 5'h0a;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h0a;
            12'h017:
                palette_index = 5'h09;
            12'h018:
                palette_index = 5'h0a;
            12'h019:
                palette_index = 5'h09;
            12'h01a:
                palette_index = 5'h0a;
            12'h01b:
                palette_index = 5'h09;
            12'h01c:
                palette_index = 5'h0a;
            12'h01d:
                palette_index = 5'h09;
            12'h01e:
                palette_index = 5'h0a;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h0a;
            12'h021:
                palette_index = 5'h09;
            12'h022:
                palette_index = 5'h10;
          endcase
      12'h007:
          casez (\$245 )
            12'h006:
                palette_index = 5'h0b;
            12'h007:
                palette_index = 5'h07;
            12'h008:
                palette_index = 5'h07;
            12'h009:
                palette_index = 5'h09;
            12'h00a:
                palette_index = 5'h09;
            12'h00b:
                palette_index = 5'h10;
            12'h00c:
                palette_index = 5'h0c;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h0c;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h0c;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h0c;
            12'h013:
                palette_index = 5'h0f;
            12'h014:
                palette_index = 5'h0c;
            12'h015:
                palette_index = 5'h0f;
            12'h016:
                palette_index = 5'h0a;
            12'h017:
                palette_index = 5'h0f;
            12'h018:
                palette_index = 5'h0a;
            12'h019:
                palette_index = 5'h0a;
            12'h01a:
                palette_index = 5'h09;
            12'h01b:
                palette_index = 5'h0a;
            12'h01c:
                palette_index = 5'h09;
            12'h01d:
                palette_index = 5'h0a;
            12'h01e:
                palette_index = 5'h09;
            12'h01f:
                palette_index = 5'h0a;
            12'h020:
                palette_index = 5'h09;
            12'h021:
                palette_index = 5'h0a;
            12'h022:
                palette_index = 5'h09;
            12'h023:
                palette_index = 5'h15;
          endcase
      12'h008:
          casez (\$247 )
            12'h005:
                palette_index = 5'h07;
            12'h006:
                palette_index = 5'h07;
            12'h007:
                palette_index = 5'h07;
            12'h008:
                palette_index = 5'h0c;
            12'h009:
                palette_index = 5'h0c;
            12'h00a:
                palette_index = 5'h12;
            12'h00b:
                palette_index = 5'h10;
            12'h00c:
                palette_index = 5'h12;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h10;
            12'h00f:
                palette_index = 5'h0c;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h0c;
            12'h012:
                palette_index = 5'h12;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h12;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h12;
            12'h017:
                palette_index = 5'h0f;
            12'h018:
                palette_index = 5'h12;
            12'h019:
                palette_index = 5'h0a;
            12'h01a:
                palette_index = 5'h0a;
            12'h01b:
                palette_index = 5'h09;
            12'h01c:
                palette_index = 5'h0a;
            12'h01d:
                palette_index = 5'h09;
            12'h01e:
                palette_index = 5'h0a;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h0c;
            12'h021:
                palette_index = 5'h09;
            12'h022:
                palette_index = 5'h0c;
            12'h023:
                palette_index = 5'h09;
            12'h024:
                palette_index = 5'h1a;
          endcase
      12'h009:
          casez (\$249 )
            12'h004:
                palette_index = 5'h0b;
            12'h005:
                palette_index = 5'h07;
            12'h006:
                palette_index = 5'h07;
            12'h007:
                palette_index = 5'h10;
            12'h008:
                palette_index = 5'h10;
            12'h009:
                palette_index = 5'h12;
            12'h00a:
                palette_index = 5'h10;
            12'h00b:
                palette_index = 5'h12;
            12'h00c:
                palette_index = 5'h10;
            12'h00d:
                palette_index = 5'h12;
            12'h00e:
                palette_index = 5'h10;
            12'h00f:
                palette_index = 5'h12;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h12;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h12;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h17;
            12'h016:
                palette_index = 5'h12;
            12'h017:
                palette_index = 5'h17;
            12'h018:
                palette_index = 5'h12;
            12'h019:
                palette_index = 5'h17;
            12'h01a:
                palette_index = 5'h0a;
            12'h01b:
                palette_index = 5'h0f;
            12'h01c:
                palette_index = 5'h09;
            12'h01d:
                palette_index = 5'h0a;
            12'h01e:
                palette_index = 5'h09;
            12'h01f:
                palette_index = 5'h0c;
            12'h020:
                palette_index = 5'h09;
            12'h021:
                palette_index = 5'h0c;
            12'h022:
                palette_index = 5'h09;
            12'h023:
                palette_index = 5'h0c;
            12'h024:
                palette_index = 5'h09;
          endcase
      12'h00a:
          casez (\$251 )
            12'h003:
                palette_index = 5'h1f;
            12'h004:
                palette_index = 5'h07;
            12'h005:
                palette_index = 5'h09;
            12'h006:
                palette_index = 5'h10;
            12'h007:
                palette_index = 5'h10;
            12'h008:
                palette_index = 5'h12;
            12'h009:
                palette_index = 5'h10;
            12'h00a:
                palette_index = 5'h12;
            12'h00b:
                palette_index = 5'h10;
            12'h00c:
                palette_index = 5'h12;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h12;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h12;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h12;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h12;
            12'h015:
                palette_index = 5'h12;
            12'h016:
                palette_index = 5'h18;
            12'h017:
                palette_index = 5'h18;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h12;
            12'h01a:
                palette_index = 5'h17;
            12'h01b:
                palette_index = 5'h0f;
            12'h01c:
                palette_index = 5'h0f;
            12'h01d:
                palette_index = 5'h0a;
            12'h01e:
                palette_index = 5'h0f;
            12'h01f:
                palette_index = 5'h0c;
            12'h020:
                palette_index = 5'h0f;
            12'h021:
                palette_index = 5'h0c;
            12'h022:
                palette_index = 5'h0c;
            12'h023:
                palette_index = 5'h09;
            12'h024:
                palette_index = 5'h0c;
            12'h025:
                palette_index = 5'h18;
          endcase
      12'h00b:
          casez (\$253 )
            12'h002:
                palette_index = 5'h1d;
            12'h003:
                palette_index = 5'h0e;
            12'h004:
                palette_index = 5'h07;
            12'h005:
                palette_index = 5'h0c;
            12'h006:
                palette_index = 5'h10;
            12'h007:
                palette_index = 5'h12;
            12'h008:
                palette_index = 5'h10;
            12'h009:
                palette_index = 5'h12;
            12'h00a:
                palette_index = 5'h10;
            12'h00b:
                palette_index = 5'h12;
            12'h00c:
                palette_index = 5'h10;
            12'h00d:
                palette_index = 5'h12;
            12'h00e:
                palette_index = 5'h10;
            12'h00f:
                palette_index = 5'h12;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h12;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h12;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h17;
            12'h016:
                palette_index = 5'h18;
            12'h017:
                palette_index = 5'h1a;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h17;
            12'h01c:
                palette_index = 5'h0f;
            12'h01d:
                palette_index = 5'h0f;
            12'h01e:
                palette_index = 5'h0c;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h0c;
            12'h023:
                palette_index = 5'h0c;
            12'h024:
                palette_index = 5'h09;
            12'h025:
                palette_index = 5'h0c;
          endcase
      12'h00c:
          casez (\$255 )
            12'h002:
                palette_index = 5'h1b;
            12'h003:
                palette_index = 5'h0b;
            12'h004:
                palette_index = 5'h0c;
            12'h005:
                palette_index = 5'h0c;
            12'h006:
                palette_index = 5'h12;
            12'h007:
                palette_index = 5'h10;
            12'h008:
                palette_index = 5'h12;
            12'h009:
                palette_index = 5'h10;
            12'h00a:
                palette_index = 5'h12;
            12'h00b:
                palette_index = 5'h10;
            12'h00c:
                palette_index = 5'h12;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h12;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h12;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h12;
            12'h013:
                palette_index = 5'h0c;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h1a;
            12'h017:
                palette_index = 5'h18;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h12;
            12'h01c:
                palette_index = 5'h12;
            12'h01d:
                palette_index = 5'h0a;
            12'h01e:
                palette_index = 5'h0f;
            12'h01f:
                palette_index = 5'h0f;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h0c;
            12'h024:
                palette_index = 5'h0c;
            12'h025:
                palette_index = 5'h09;
            12'h026:
                palette_index = 5'h10;
          endcase
      12'h00d:
          casez (\$257 )
            12'h001:
                palette_index = 5'h1f;
            12'h002:
                palette_index = 5'h0d;
            12'h003:
                palette_index = 5'h04;
            12'h004:
                palette_index = 5'h09;
            12'h005:
                palette_index = 5'h12;
            12'h006:
                palette_index = 5'h10;
            12'h007:
                palette_index = 5'h17;
            12'h008:
                palette_index = 5'h15;
            12'h009:
                palette_index = 5'h18;
            12'h00a:
                palette_index = 5'h15;
            12'h00b:
                palette_index = 5'h12;
            12'h00c:
                palette_index = 5'h10;
            12'h00d:
                palette_index = 5'h12;
            12'h00e:
                palette_index = 5'h10;
            12'h00f:
                palette_index = 5'h12;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h12;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h09;
            12'h014:
                palette_index = 5'h05;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h13;
            12'h017:
                palette_index = 5'h1a;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h17;
            12'h01c:
                palette_index = 5'h0f;
            12'h01d:
                palette_index = 5'h0f;
            12'h01e:
                palette_index = 5'h09;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h10;
            12'h025:
                palette_index = 5'h10;
            12'h026:
                palette_index = 5'h09;
            12'h027:
                palette_index = 5'h18;
          endcase
      12'h00e:
          casez (\$259 )
            12'h001:
                palette_index = 5'h1f;
            12'h002:
                palette_index = 5'h0b;
            12'h003:
                palette_index = 5'h02;
            12'h004:
                palette_index = 5'h0c;
            12'h005:
                palette_index = 5'h10;
            12'h006:
                palette_index = 5'h15;
            12'h007:
                palette_index = 5'h13;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h13;
            12'h00a:
                palette_index = 5'h18;
            12'h00b:
                palette_index = 5'h15;
            12'h00c:
                palette_index = 5'h15;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h12;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h12;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h12;
            12'h013:
                palette_index = 5'h05;
            12'h014:
                palette_index = 5'h04;
            12'h015:
                palette_index = 5'h05;
            12'h016:
                palette_index = 5'h15;
            12'h017:
                palette_index = 5'h17;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h12;
            12'h01c:
                palette_index = 5'h12;
            12'h01d:
                palette_index = 5'h09;
            12'h01e:
                palette_index = 5'h12;
            12'h01f:
                palette_index = 5'h10;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h12;
            12'h025:
                palette_index = 5'h10;
            12'h026:
                palette_index = 5'h10;
            12'h027:
                palette_index = 5'h0c;
          endcase
      12'h00f:
          casez (\$261 )
            12'h001:
                palette_index = 5'h1f;
            12'h002:
                palette_index = 5'h07;
            12'h003:
                palette_index = 5'h04;
            12'h004:
                palette_index = 5'h09;
            12'h005:
                palette_index = 5'h15;
            12'h006:
                palette_index = 5'h15;
            12'h007:
                palette_index = 5'h18;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h1a;
            12'h00a:
                palette_index = 5'h18;
            12'h00b:
                palette_index = 5'h1a;
            12'h00c:
                palette_index = 5'h13;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h13;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h06;
            12'h014:
                palette_index = 5'h02;
            12'h015:
                palette_index = 5'h04;
            12'h016:
                palette_index = 5'h09;
            12'h017:
                palette_index = 5'h12;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h17;
            12'h01c:
                palette_index = 5'h0a;
            12'h01d:
                palette_index = 5'h12;
            12'h01e:
                palette_index = 5'h10;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h17;
            12'h024:
                palette_index = 5'h12;
            12'h025:
                palette_index = 5'h12;
            12'h026:
                palette_index = 5'h10;
            12'h027:
                palette_index = 5'h10;
          endcase
      12'h010:
          casez (\$263 )
            12'h000:
                palette_index = 5'h1f;
            12'h001:
                palette_index = 5'h1c;
            12'h002:
                palette_index = 5'h07;
            12'h003:
                palette_index = 5'h02;
            12'h004:
                palette_index = 5'h09;
            12'h005:
                palette_index = 5'h10;
            12'h006:
                palette_index = 5'h18;
            12'h007:
                palette_index = 5'h18;
            12'h008:
                palette_index = 5'h1a;
            12'h009:
                palette_index = 5'h1a;
            12'h00a:
                palette_index = 5'h1b;
            12'h00b:
                palette_index = 5'h18;
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h15;
            12'h013:
                palette_index = 5'h05;
            12'h014:
                palette_index = 5'h04;
            12'h015:
                palette_index = 5'h02;
            12'h016:
                palette_index = 5'h09;
            12'h017:
                palette_index = 5'h0c;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h0f;
            12'h01c:
                palette_index = 5'h12;
            12'h01d:
                palette_index = 5'h12;
            12'h01e:
                palette_index = 5'h18;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h17;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h17;
            12'h025:
                palette_index = 5'h12;
            12'h026:
                palette_index = 5'h12;
            12'h027:
                palette_index = 5'h10;
          endcase
      12'h011:
          casez (\$265 )
            12'h000:
                palette_index = 5'h1d;
            12'h001:
                palette_index = 5'h1b;
            12'h002:
                palette_index = 5'h07;
            12'h003:
                palette_index = 5'h0b;
            12'h004:
                palette_index = 5'h07;
            12'h005:
                palette_index = 5'h15;
            12'h006:
                palette_index = 5'h13;
            12'h007:
                palette_index = 5'h1a;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h1b;
            12'h00a:
                palette_index = 5'h1b;
            12'h00b:
                palette_index = 5'h1b;
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h09;
            12'h014:
                palette_index = 5'h02;
            12'h015:
                palette_index = 5'h03;
            12'h016:
                palette_index = 5'h04;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h12;
            12'h01b:
                palette_index = 5'h12;
            12'h01c:
                palette_index = 5'h12;
            12'h01d:
                palette_index = 5'h17;
            12'h01e:
                palette_index = 5'h17;
            12'h01f:
                palette_index = 5'h17;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h17;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h17;
            12'h024:
                palette_index = 5'h12;
            12'h025:
                palette_index = 5'h17;
            12'h026:
                palette_index = 5'h12;
            12'h027:
                palette_index = 5'h12;
          endcase
      12'h012:
          casez (\$267 )
            12'h000:
                palette_index = 5'h1f;
            12'h001:
                palette_index = 5'h1b;
            12'h002:
                palette_index = 5'h0b;
            12'h003:
                palette_index = 5'h07;
            12'h004:
                palette_index = 5'h0b;
            12'h005:
                palette_index = 5'h10;
            12'h006:
                palette_index = 5'h18;
            12'h007:
                palette_index = 5'h18;
            12'h008:
                palette_index = 5'h1a;
            12'h009:
                palette_index = 5'h1a;
            12'h00a:
                palette_index = 5'h1b;
            12'h00b:
                palette_index = 5'h1a;
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h05;
            12'h015:
                palette_index = 5'h02;
            12'h016:
                palette_index = 5'h06;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h13;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h12;
            12'h01c:
                palette_index = 5'h17;
            12'h01d:
                palette_index = 5'h10;
            12'h01e:
                palette_index = 5'h17;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h17;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h17;
            12'h025:
                palette_index = 5'h12;
            12'h026:
                palette_index = 5'h17;
            12'h027:
                palette_index = 5'h10;
          endcase
      12'h013:
          casez (\$269 )
            12'h000:
                palette_index = 5'h1d;
            12'h001:
                palette_index = 5'h1e;
            12'h002:
                palette_index = 5'h11;
            12'h003:
                palette_index = 5'h07;
            12'h004:
                palette_index = 5'h0b;
            12'h005:
                palette_index = 5'h15;
            12'h006:
                palette_index = 5'h18;
            12'h007:
                palette_index = 5'h1a;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h1a;
            12'h00a:
                palette_index = 5'h18;
            12'h00b:
                palette_index = 5'h1a;
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h05;
            12'h015:
                palette_index = 5'h06;
            12'h016:
                palette_index = 5'h09;
            12'h017:
                palette_index = 5'h17;
            12'h018:
                palette_index = 5'h17;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h17;
            12'h01b:
                palette_index = 5'h17;
            12'h01c:
                palette_index = 5'h17;
            12'h01d:
                palette_index = 5'h12;
            12'h01e:
                palette_index = 5'h10;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h12;
            12'h025:
                palette_index = 5'h17;
            12'h026:
                palette_index = 5'h12;
            12'h027:
                palette_index = 5'h17;
          endcase
      12'h014:
          casez (\$271 )
            12'h000:
                palette_index = 5'h1f;
            12'h001:
                palette_index = 5'h1b;
            12'h002:
                palette_index = 5'h0e;
            12'h003:
                palette_index = 5'h07;
            12'h004:
                palette_index = 5'h14;
            12'h005:
                palette_index = 5'h16;
            12'h006:
                palette_index = 5'h18;
            12'h007:
                palette_index = 5'h18;
            12'h008:
                palette_index = 5'h1a;
            12'h009:
                palette_index = 5'h18;
            12'h00a:
                palette_index = 5'h1a;
            12'h00b:
                palette_index = 5'h18;
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h13;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h12;
            12'h017:
                palette_index = 5'h17;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h13;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h1a;
            12'h01d:
                palette_index = 5'h17;
            12'h01e:
                palette_index = 5'h12;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h10;
            12'h024:
                palette_index = 5'h17;
            12'h025:
                palette_index = 5'h12;
            12'h026:
                palette_index = 5'h17;
            12'h027:
                palette_index = 5'h12;
          endcase
      12'h015:
          casez (\$273 )
            12'h000:
                palette_index = 5'h1d;
            12'h001:
                palette_index = 5'h1f;
            12'h002:
                palette_index = 5'h0e;
            12'h003:
                palette_index = 5'h0e;
            12'h004:
                palette_index = 5'h14;
            12'h005:
                palette_index = 5'h1e;
            12'h006:
                palette_index = 5'h18;
            12'h007:
                palette_index = 5'h1a;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h1a;
            12'h00a:
                palette_index = 5'h18;
            12'h00b:
                palette_index = 5'h1a;
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h1a;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h12;
            12'h016:
                palette_index = 5'h10;
            12'h017:
                palette_index = 5'h1a;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h1a;
            12'h01c:
                palette_index = 5'h1a;
            12'h01d:
                palette_index = 5'h1a;
            12'h01e:
                palette_index = 5'h10;
            12'h01f:
                palette_index = 5'h0c;
            12'h020:
                palette_index = 5'h0c;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h12;
            12'h025:
                palette_index = 5'h17;
            12'h026:
                palette_index = 5'h12;
            12'h027:
                palette_index = 5'h17;
          endcase
      12'h016:
          casez (\$275 )
            12'h001:
                palette_index = 5'h1d;
            12'h002:
                palette_index = 5'h16;
            12'h003:
                palette_index = 5'h0e;
            12'h004:
                palette_index = 5'h16;
            12'h005:
                palette_index = 5'h19;
            12'h006:
                palette_index = 5'h1a;
            12'h007:
                palette_index = 5'h18;
            12'h008:
                palette_index = 5'h1a;
            12'h009:
                palette_index = 5'h18;
            12'h00a:
                palette_index = 5'h1a;
            12'h00b:
                palette_index = 5'h18;
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h0c;
            12'h016:
                palette_index = 5'h0c;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h1a;
            12'h01d:
                palette_index = 5'h13;
            12'h01e:
                palette_index = 5'h12;
            12'h01f:
                palette_index = 5'h0c;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h10;
            12'h024:
                palette_index = 5'h17;
            12'h025:
                palette_index = 5'h12;
            12'h026:
                palette_index = 5'h17;
            12'h027:
                palette_index = 5'h1a;
          endcase
      12'h017:
          casez (\$277 )
            12'h001:
                palette_index = 5'h1f;
            12'h002:
                palette_index = 5'h16;
            12'h003:
                palette_index = 5'h16;
            12'h004:
                palette_index = 5'h16;
            12'h005:
                palette_index = 5'h1b;
            12'h006:
                palette_index = 5'h1a;
            12'h007:
                palette_index = 5'h1a;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h1a;
            12'h00a:
                palette_index = 5'h18;
            12'h00b:
                palette_index = 5'h1a;
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h1a;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h02;
            12'h017:
                palette_index = 5'h05;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h10;
            12'h01d:
                palette_index = 5'h10;
            12'h01e:
                palette_index = 5'h0c;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h0c;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h12;
            12'h025:
                palette_index = 5'h17;
            12'h026:
                palette_index = 5'h18;
          endcase
      12'h018:
          casez (\$279 )
            12'h001:
                palette_index = 5'h1d;
            12'h002:
                palette_index = 5'h1b;
            12'h003:
                palette_index = 5'h16;
            12'h004:
                palette_index = 5'h1e;
            12'h005:
                palette_index = 5'h19;
            12'h006:
                palette_index = 5'h1b;
            12'h007:
                palette_index = 5'h18;
            12'h008:
                palette_index = 5'h1a;
            12'h009:
                palette_index = 5'h1a;
            12'h00a:
                palette_index = 5'h1b;
            12'h00b:
                palette_index = 5'h18;
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h12;
            12'h015:
                palette_index = 5'h04;
            12'h016:
                palette_index = 5'h01;
            12'h017:
                palette_index = 5'h01;
            12'h018:
                palette_index = 5'h10;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h10;
            12'h01d:
                palette_index = 5'h06;
            12'h01e:
                palette_index = 5'h06;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h09;
            12'h021:
                palette_index = 5'h0c;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h10;
            12'h024:
                palette_index = 5'h12;
            12'h025:
                palette_index = 5'h10;
          endcase
      12'h019:
          casez (\$281 )
            12'h002:
                palette_index = 5'h1d;
            12'h003:
                palette_index = 5'h1e;
            12'h004:
                palette_index = 5'h19;
            12'h005:
                palette_index = 5'h1b;
            12'h006:
                palette_index = 5'h18;
            12'h007:
                palette_index = 5'h1a;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h1b;
            12'h00a:
                palette_index = 5'h1a;
            12'h00b:
                palette_index = 5'h1b;
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h1a;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h04;
            12'h016:
                palette_index = 5'h02;
            12'h017:
                palette_index = 5'h03;
            12'h018:
                palette_index = 5'h10;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h1a;
            12'h01c:
                palette_index = 5'h13;
            12'h01d:
                palette_index = 5'h0c;
            12'h01e:
                palette_index = 5'h05;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h09;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h10;
          endcase
      12'h01a:
          casez (\$283 )
            12'h003:
                palette_index = 5'h1b;
            12'h004:
                palette_index = 5'h1b;
            12'h005:
                palette_index = 5'h16;
            12'h006:
                palette_index = 5'h1a;
            12'h007:
                palette_index = 5'h18;
            12'h008:
                palette_index = 5'h1a;
            12'h009:
                palette_index = 5'h1a;
            12'h00a:
                palette_index = 5'h1b;
            12'h00b:
                palette_index = 5'h1a;
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h04;
            12'h016:
                palette_index = 5'h01;
            12'h017:
                palette_index = 5'h01;
            12'h018:
                palette_index = 5'h15;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h1a;
            12'h01c:
                palette_index = 5'h1a;
            12'h01d:
                palette_index = 5'h10;
            12'h01e:
                palette_index = 5'h0a;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h1a;
          endcase
      12'h01b:
          casez (\$285 )
            12'h004:
                palette_index = 5'h16;
            12'h005:
                palette_index = 5'h18;
            12'h006:
                palette_index = 5'h18;
            12'h007:
                palette_index = 5'h18;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h1b;
            12'h00a:
                palette_index = 5'h1b;
            12'h00b:
                palette_index = 5'h1e;
            12'h00c:
                palette_index = 5'h1b;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h1a;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h01;
            12'h017:
                palette_index = 5'h04;
            12'h018:
                palette_index = 5'h15;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h1a;
            12'h01c:
                palette_index = 5'h18;
            12'h01d:
                palette_index = 5'h12;
            12'h01e:
                palette_index = 5'h0a;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h1a;
            12'h022:
                palette_index = 5'h1e;
          endcase
      12'h01c:
          casez (\$287 )
            12'h004:
                palette_index = 5'h1f;
            12'h005:
                palette_index = 5'h16;
            12'h006:
                palette_index = 5'h18;
            12'h007:
                palette_index = 5'h13;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h18;
            12'h00a:
                palette_index = 5'h1e;
            12'h00b:
                palette_index = 5'h1b;
            12'h00c:
                palette_index = 5'h1e;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h18;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h05;
            12'h017:
                palette_index = 5'h05;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h18;
            12'h01d:
                palette_index = 5'h10;
            12'h01e:
                palette_index = 5'h12;
            12'h01f:
                palette_index = 5'h15;
            12'h020:
                palette_index = 5'h1f;
          endcase
      12'h01d:
          casez (\$289 )
            12'h005:
                palette_index = 5'h1f;
            12'h006:
                palette_index = 5'h16;
            12'h007:
                palette_index = 5'h18;
            12'h008:
                palette_index = 5'h16;
            12'h009:
                palette_index = 5'h1a;
            12'h00a:
                palette_index = 5'h18;
            12'h00b:
                palette_index = 5'h1a;
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h15;
            12'h011:
                palette_index = 5'h15;
            12'h012:
                palette_index = 5'h15;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h09;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h13;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h13;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h18;
            12'h01d:
                palette_index = 5'h1e;
          endcase
      12'h01e:
          casez (\$291 )
            12'h006:
                palette_index = 5'h1f;
            12'h007:
                palette_index = 5'h16;
            12'h008:
                palette_index = 5'h18;
            12'h009:
                palette_index = 5'h13;
            12'h00a:
                palette_index = 5'h18;
            12'h00b:
                palette_index = 5'h18;
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h15;
            12'h010:
                palette_index = 5'h15;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h15;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h0c;
            12'h016:
                palette_index = 5'h0c;
            12'h017:
                palette_index = 5'h0c;
            12'h018:
                palette_index = 5'h15;
            12'h019:
                palette_index = 5'h10;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h1b;
          endcase
      12'h01f:
          casez (\$293 )
            12'h007:
                palette_index = 5'h1f;
            12'h008:
                palette_index = 5'h11;
            12'h009:
                palette_index = 5'h18;
            12'h00a:
                palette_index = 5'h13;
            12'h00b:
                palette_index = 5'h18;
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h15;
            12'h00f:
                palette_index = 5'h15;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h15;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h0c;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h0c;
            12'h017:
                palette_index = 5'h15;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h1e;
          endcase
      12'h020:
          casez (\$295 )
            12'h008:
                palette_index = 5'h1b;
            12'h009:
                palette_index = 5'h11;
            12'h00a:
                palette_index = 5'h16;
            12'h00b:
                palette_index = 5'h16;
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h13;
            12'h00e:
                palette_index = 5'h15;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h15;
            12'h011:
                palette_index = 5'h0e;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h0e;
            12'h014:
                palette_index = 5'h1b;
            12'h015:
                palette_index = 5'h1b;
          endcase
    endcase
  end
  assign \$1  = \$2 ;
  assign \$6  = \$7 ;
endmodule
