/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post95, git sha1 a1bb0255d) */

module sphn_vga_top(o_g, o_b, o_hsync, o_vsync, i_move_up, i_move_down, pix_clk, pix_rst, o_r);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire \$1 ;
  wire \$100 ;
  wire \$102 ;
  wire [3:0] \$104 ;
  wire [3:0] \$105 ;
  wire \$107 ;
  wire [3:0] \$109 ;
  wire [11:0] \$11 ;
  wire [3:0] \$110 ;
  wire \$112 ;
  wire \$114 ;
  wire \$116 ;
  wire \$118 ;
  wire [10:0] \$12 ;
  wire [10:0] \$120 ;
  wire [10:0] \$121 ;
  wire \$123 ;
  wire \$125 ;
  wire [10:0] \$127 ;
  wire [10:0] \$128 ;
  wire \$130 ;
  wire \$132 ;
  wire [11:0] \$134 ;
  wire [10:0] \$136 ;
  wire [11:0] \$138 ;
  wire [10:0] \$14 ;
  wire \$140 ;
  wire \$142 ;
  wire \$144 ;
  wire [10:0] \$146 ;
  wire [10:0] \$147 ;
  wire [11:0] \$149 ;
  wire [4:0] \$15 ;
  wire [10:0] \$151 ;
  wire [11:0] \$153 ;
  wire \$155 ;
  wire \$157 ;
  wire \$159 ;
  wire [10:0] \$161 ;
  wire [10:0] \$162 ;
  wire [11:0] \$18 ;
  wire \$20 ;
  wire \$22 ;
  wire \$24 ;
  wire \$26 ;
  wire \$28 ;
  wire \$3 ;
  wire [10:0] \$30 ;
  wire [10:0] \$32 ;
  wire \$34 ;
  wire [10:0] \$36 ;
  wire \$38 ;
  wire \$40 ;
  wire \$42 ;
  wire \$44 ;
  wire [10:0] \$46 ;
  wire [10:0] \$48 ;
  wire [10:0] \$5 ;
  wire \$50 ;
  wire [10:0] \$52 ;
  wire \$54 ;
  wire \$56 ;
  wire \$58 ;
  wire [10:0] \$6 ;
  wire \$60 ;
  wire \$62 ;
  wire \$64 ;
  wire [3:0] \$66 ;
  wire [3:0] \$67 ;
  wire [3:0] \$69 ;
  wire [3:0] \$71 ;
  wire \$72 ;
  wire \$75 ;
  wire [3:0] \$77 ;
  wire [3:0] \$78 ;
  wire [10:0] \$8 ;
  wire [3:0] \$80 ;
  wire [3:0] \$82 ;
  wire \$83 ;
  wire \$86 ;
  wire [10:0] \$88 ;
  wire [10:0] \$9 ;
  wire [10:0] \$90 ;
  wire \$92 ;
  wire [10:0] \$94 ;
  wire \$96 ;
  wire \$98 ;
  reg [9:0] enemy_paddle_location = 10'h0a5;
  reg [9:0] \enemy_paddle_location$next ;
  input i_move_down;
  wire i_move_down;
  input i_move_up;
  wire i_move_up;
  output [2:0] o_b;
  wire [2:0] o_b;
  output [2:0] o_g;
  wire [2:0] o_g;
  output o_hsync;
  wire o_hsync;
  output [2:0] o_r;
  wire [2:0] o_r;
  output o_vsync;
  wire o_vsync;
  reg [9:0] paddle_location = 10'h0a5;
  reg [9:0] \paddle_location$next ;
  input pix_clk;
  wire pix_clk;
  input pix_rst;
  wire pix_rst;
  reg pope_h_velocity = 1'h0;
  reg \pope_h_velocity$next ;
  reg [19:0] pope_location = 20'h4b0df;
  reg [19:0] \pope_location$next ;
  reg [2:0] pope_v_velocity = 3'h7;
  reg [2:0] \pope_v_velocity$next ;
  reg prev_vsync = 1'h0;
  reg \prev_vsync$next ;
  wire vga_i_enable;
  wire [9:0] vga_i_enemy_paddle_location;
  wire [9:0] vga_i_paddle_location;
  wire [19:0] vga_i_pope_location;
  wire [2:0] vga_o_b;
  wire [2:0] vga_o_g;
  wire vga_o_hsync;
  wire [2:0] vga_o_r;
  wire vga_o_vsync;
  assign \$9  = pope_location[9:0] - 2'h3;
  assign \$100  = \$86  & \$98 ;
  assign \$102  = $signed(pope_v_velocity) > $signed(3'h5);
  assign \$105  = $signed(pope_v_velocity) - $signed(3'h1);
  assign \$107  = $signed(pope_v_velocity) < $signed(3'h3);
  assign \$110  = $signed(pope_v_velocity) + $signed(3'h1);
  assign \$112  = ~ vga_o_vsync;
  assign \$114  = prev_vsync & \$112 ;
  assign \$116  = paddle_location >= 2'h3;
  assign \$118  = i_move_up & \$116 ;
  assign \$121  = paddle_location - 2'h3;
  assign \$123  = paddle_location < 9'h147;
  assign \$125  = i_move_down & \$123 ;
  assign \$128  = paddle_location + 2'h3;
  assign \$12  = + pope_location[19:10];
  assign \$130  = ~ vga_o_vsync;
  assign \$132  = prev_vsync & \$130 ;
  assign \$134  = + pope_location[19:10];
  assign \$136  = enemy_paddle_location + 7'h4b;
  assign \$138  = \$136  - 5'h14;
  assign \$140  = $signed(\$134 ) > $signed(\$138 );
  assign \$142  = enemy_paddle_location < 9'h136;
  assign \$144  = \$140  & \$142 ;
  assign \$147  = enemy_paddle_location + 2'h2;
  assign \$149  = + pope_location[19:10];
  assign \$151  = enemy_paddle_location + 7'h4b;
  assign \$153  = \$151  - 5'h14;
  assign \$155  = $signed(\$149 ) < $signed(\$153 );
  assign \$157  = enemy_paddle_location > 5'h14;
  assign \$15  = $signed(3'h3) * $signed(pope_v_velocity);
  assign \$159  = \$155  & \$157 ;
  assign \$162  = enemy_paddle_location - 2'h2;
  always @(posedge pix_clk)
    prev_vsync <= \prev_vsync$next ;
  always @(posedge pix_clk)
    pope_location <= \pope_location$next ;
  always @(posedge pix_clk)
    pope_h_velocity <= \pope_h_velocity$next ;
  always @(posedge pix_clk)
    pope_v_velocity <= \pope_v_velocity$next ;
  always @(posedge pix_clk)
    paddle_location <= \paddle_location$next ;
  always @(posedge pix_clk)
    enemy_paddle_location <= \enemy_paddle_location$next ;
  assign \$14  = + $signed(\$15 );
  assign \$18  = $signed(\$12 ) + $signed(\$14 );
  assign \$1  = ~ vga_o_vsync;
  assign \$20  = ~ vga_o_vsync;
  assign \$22  = prev_vsync & \$20 ;
  assign \$24  = pope_location[9:0] <= 3'h6;
  assign \$26  = pope_location[9:0] >= 10'h25e;
  assign \$28  = pope_location[9:0] < 6'h32;
  assign \$30  = + pope_location[19:10];
  assign \$32  = paddle_location - 6'h28;
  assign \$34  = $signed(\$30 ) > $signed(\$32 );
  assign \$36  = paddle_location + 8'h96;
  assign \$38  = pope_location[19:10] <= \$36 ;
  assign \$3  = prev_vsync & \$1 ;
  assign \$40  = \$34  & \$38 ;
  assign \$42  = \$28  & \$40 ;
  assign \$44  = pope_location[9:0] >= 10'h22c;
  assign \$46  = + pope_location[19:10];
  assign \$48  = enemy_paddle_location - 6'h28;
  assign \$50  = $signed(\$46 ) > $signed(\$48 );
  assign \$52  = enemy_paddle_location + 8'h96;
  assign \$54  = pope_location[19:10] <= \$52 ;
  assign \$56  = \$50  & \$54 ;
  assign \$58  = \$44  & \$56 ;
  assign \$60  = ~ vga_o_vsync;
  assign \$62  = prev_vsync & \$60 ;
  assign \$64  = pope_location[19:10] <= 5'h14;
  assign \$67  = + $signed(pope_v_velocity);
  assign \$6  = pope_location[9:0] + 2'h3;
  assign \$69  = - $signed(pope_v_velocity);
  assign \$72  = $signed(pope_v_velocity) > $signed(3'h0);
  assign \$71  = \$72  ? \$67  : \$69 ;
  assign \$75  = pope_location[19:10] >= 9'h1b8;
  assign \$78  = + $signed(pope_v_velocity);
  assign \$80  = - $signed(pope_v_velocity);
  assign \$83  = $signed(pope_v_velocity) < $signed(3'h0);
  assign \$82  = \$83  ? \$78  : \$80 ;
  assign \$86  = pope_location[9:0] < 6'h32;
  assign \$88  = + pope_location[19:10];
  assign \$90  = paddle_location - 6'h28;
  assign \$92  = $signed(\$88 ) > $signed(\$90 );
  assign \$94  = paddle_location + 8'h96;
  assign \$96  = pope_location[19:10] <= \$94 ;
  assign \$98  = \$92  & \$96 ;
  \sphn_vga_top.vga  vga (
    .i_enable(1'h1),
    .i_enemy_paddle_location(vga_i_enemy_paddle_location),
    .i_paddle_location(vga_i_paddle_location),
    .i_pope_location(vga_i_pope_location),
    .o_b(vga_o_b),
    .o_g(vga_o_g),
    .o_hsync(vga_o_hsync),
    .o_r(vga_o_r),
    .o_vsync(vga_o_vsync),
    .pix_clk(pix_clk),
    .pix_rst(pix_rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \prev_vsync$next  = vga_o_vsync;
    if (pix_rst) begin
      \prev_vsync$next  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \pope_location$next  = pope_location;
    if (\$3 ) begin
      (* full_case = 32'd1 *)
      if (pope_h_velocity) begin
        \pope_location$next [9:0] = \$6 [9:0];
      end else begin
        \pope_location$next [9:0] = \$9 [9:0];
      end
      begin
          \pope_location$next [19:10] = \$18 [9:0];
      end
    end
    if (pix_rst) begin
      \pope_location$next  = 20'h4b0df;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \pope_h_velocity$next  = pope_h_velocity;
    if (\$22 ) begin
      if (\$24 ) begin
        \pope_h_velocity$next  = 1'h1;
      end
      if (\$26 ) begin
        \pope_h_velocity$next  = 1'h0;
      end
      if (\$42 ) begin
        \pope_h_velocity$next  = 1'h1;
      end
      if (\$58 ) begin
        \pope_h_velocity$next  = 1'h0;
      end
    end
    if (pix_rst) begin
      \pope_h_velocity$next  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \pope_v_velocity$next  = pope_v_velocity;
    if (\$62 ) begin
      if (\$64 ) begin
        \pope_v_velocity$next  = \$71 [2:0];
      end
      if (\$75 ) begin
        \pope_v_velocity$next  = \$82 [2:0];
      end
      if (\$100 ) begin
        if (i_move_up) begin
          if (\$102 ) begin
            \pope_v_velocity$next  = \$105 [2:0];
          end
        end
        if (i_move_down) begin
          if (\$107 ) begin
            \pope_v_velocity$next  = \$110 [2:0];
          end
        end
      end
    end
    if (pix_rst) begin
      \pope_v_velocity$next  = 3'h7;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \paddle_location$next  = paddle_location;
    if (\$114 ) begin
      if (\$118 ) begin
        \paddle_location$next  = \$121 [9:0];
      end
      if (\$125 ) begin
        \paddle_location$next  = \$128 [9:0];
      end
    end
    if (pix_rst) begin
      \paddle_location$next  = 10'h0a5;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \enemy_paddle_location$next  = enemy_paddle_location;
    if (\$132 ) begin
      if (\$144 ) begin
        \enemy_paddle_location$next  = \$147 [9:0];
      end
      if (\$159 ) begin
        \enemy_paddle_location$next  = \$162 [9:0];
      end
    end
    if (pix_rst) begin
      \enemy_paddle_location$next  = 10'h0a5;
    end
  end
  assign \$5  = \$6 ;
  assign \$8  = \$9 ;
  assign \$11  = \$18 ;
  assign \$66  = \$71 ;
  assign \$77  = \$82 ;
  assign \$104  = \$105 ;
  assign \$109  = \$110 ;
  assign \$120  = \$121 ;
  assign \$127  = \$128 ;
  assign \$146  = \$147 ;
  assign \$161  = \$162 ;
  assign o_vsync = vga_o_vsync;
  assign o_hsync = vga_o_hsync;
  assign o_b = vga_o_b;
  assign o_g = vga_o_g;
  assign o_r = vga_o_r;
  assign vga_i_enemy_paddle_location = enemy_paddle_location;
  assign vga_i_paddle_location = paddle_location;
  assign vga_i_pope_location = pope_location;
  assign vga_i_enable = 1'h1;
endmodule

module \sphn_vga_top.vga (o_vsync, i_pope_location, i_paddle_location, i_enemy_paddle_location, o_r, o_g, o_b, o_hsync, pix_rst, pix_clk, i_enable);
  reg \$auto$verilog_backend.cc:2352:dump_module$2  = 0;
  wire [11:0] \$1 ;
  wire \$101 ;
  wire \$103 ;
  wire [10:0] \$105 ;
  wire \$107 ;
  wire \$109 ;
  wire \$11 ;
  wire \$111 ;
  wire \$113 ;
  wire \$115 ;
  wire \$117 ;
  wire \$119 ;
  wire \$121 ;
  wire \$123 ;
  wire \$125 ;
  wire [10:0] \$127 ;
  wire \$129 ;
  wire \$13 ;
  wire \$131 ;
  wire \$133 ;
  wire \$135 ;
  wire \$137 ;
  wire \$139 ;
  wire \$141 ;
  wire [10:0] \$143 ;
  wire \$145 ;
  wire \$147 ;
  wire \$149 ;
  wire \$15 ;
  wire \$151 ;
  wire \$153 ;
  wire \$155 ;
  wire \$157 ;
  wire \$159 ;
  wire \$161 ;
  wire \$163 ;
  wire [10:0] \$165 ;
  wire \$167 ;
  wire \$169 ;
  wire \$17 ;
  wire \$171 ;
  wire \$173 ;
  wire \$175 ;
  wire \$177 ;
  wire \$179 ;
  wire [10:0] \$181 ;
  wire \$183 ;
  wire \$185 ;
  wire \$187 ;
  wire \$189 ;
  wire \$19 ;
  wire \$191 ;
  wire \$193 ;
  wire \$195 ;
  wire \$197 ;
  wire \$199 ;
  wire [11:0] \$2 ;
  wire \$21 ;
  wire [11:0] \$23 ;
  wire [11:0] \$25 ;
  wire [11:0] \$27 ;
  wire [11:0] \$29 ;
  wire [11:0] \$31 ;
  wire [11:0] \$33 ;
  wire [11:0] \$35 ;
  wire [11:0] \$37 ;
  wire [11:0] \$39 ;
  wire \$4 ;
  wire [11:0] \$41 ;
  wire [11:0] \$43 ;
  wire [11:0] \$45 ;
  wire [11:0] \$47 ;
  wire [11:0] \$49 ;
  wire [11:0] \$51 ;
  wire [11:0] \$53 ;
  wire [11:0] \$55 ;
  wire [11:0] \$57 ;
  wire [11:0] \$59 ;
  wire [11:0] \$6 ;
  wire [11:0] \$61 ;
  wire [11:0] \$63 ;
  wire [11:0] \$65 ;
  wire [11:0] \$67 ;
  wire [11:0] \$69 ;
  wire [11:0] \$7 ;
  wire [11:0] \$71 ;
  wire [11:0] \$73 ;
  wire [11:0] \$75 ;
  wire [11:0] \$77 ;
  wire [11:0] \$79 ;
  wire [11:0] \$81 ;
  wire [11:0] \$83 ;
  wire [11:0] \$85 ;
  wire \$87 ;
  wire [10:0] \$89 ;
  wire \$9 ;
  wire \$91 ;
  wire \$93 ;
  wire \$95 ;
  wire \$97 ;
  wire \$99 ;
  reg [21:0] clock = 22'h000000;
  reg [21:0] \clock$next ;
  input i_enable;
  wire i_enable;
  input [9:0] i_enemy_paddle_location;
  wire [9:0] i_enemy_paddle_location;
  input [9:0] i_paddle_location;
  wire [9:0] i_paddle_location;
  input [19:0] i_pope_location;
  wire [19:0] i_pope_location;
  output [2:0] o_b;
  reg [2:0] o_b;
  output [2:0] o_g;
  reg [2:0] o_g;
  output o_hsync;
  reg o_hsync;
  output [2:0] o_r;
  reg [2:0] o_r;
  output o_vsync;
  reg o_vsync;
  reg [4:0] palette_index;
  input pix_clk;
  wire pix_clk;
  input pix_rst;
  wire pix_rst;
  assign \$9  = clock[21:11] == 10'h20c;
  assign \$99  = clock[10:0] < 6'h32;
  assign \$101  = \$97  & \$99 ;
  assign \$103  = clock[21:11] >= i_enemy_paddle_location;
  assign \$105  = i_enemy_paddle_location + 8'h96;
  assign \$107  = clock[21:11] < \$105 ;
  assign \$109  = \$103  & \$107 ;
  assign \$111  = clock[10:0] < 10'h267;
  assign \$113  = \$109  & \$111 ;
  assign \$115  = clock[10:0] >= 10'h24e;
  assign \$117  = \$113  & \$115 ;
  assign \$11  = clock[10:0] >= 10'h290;
  assign \$119  = clock[10:0] >= 10'h280;
  assign \$121  = clock[21:11] >= 9'h1e0;
  assign \$123  = \$119  | \$121 ;
  assign \$125  = clock[21:11] >= i_paddle_location;
  assign \$127  = i_paddle_location + 8'h96;
  assign \$129  = clock[21:11] < \$127 ;
  assign \$131  = \$125  & \$129 ;
  assign \$133  = clock[10:0] >= 5'h19;
  assign \$135  = \$131  & \$133 ;
  assign \$137  = clock[10:0] < 6'h32;
  assign \$13  = clock[10:0] < 10'h2f0;
  assign \$139  = \$135  & \$137 ;
  assign \$141  = clock[21:11] >= i_enemy_paddle_location;
  assign \$143  = i_enemy_paddle_location + 8'h96;
  assign \$145  = clock[21:11] < \$143 ;
  assign \$147  = \$141  & \$145 ;
  assign \$149  = clock[10:0] < 10'h267;
  assign \$151  = \$147  & \$149 ;
  assign \$153  = clock[10:0] >= 10'h24e;
  assign \$155  = \$151  & \$153 ;
  assign \$157  = clock[10:0] >= 10'h280;
  assign \$15  = \$11  & \$13 ;
  assign \$159  = clock[21:11] >= 9'h1e0;
  assign \$161  = \$157  | \$159 ;
  assign \$163  = clock[21:11] >= i_paddle_location;
  assign \$165  = i_paddle_location + 8'h96;
  assign \$167  = clock[21:11] < \$165 ;
  assign \$169  = \$163  & \$167 ;
  assign \$171  = clock[10:0] >= 5'h19;
  assign \$173  = \$169  & \$171 ;
  assign \$175  = clock[10:0] < 6'h32;
  assign \$177  = \$173  & \$175 ;
  assign \$17  = clock[21:11] >= 9'h1ea;
  assign \$179  = clock[21:11] >= i_enemy_paddle_location;
  assign \$181  = i_enemy_paddle_location + 8'h96;
  assign \$183  = clock[21:11] < \$181 ;
  assign \$185  = \$179  & \$183 ;
  assign \$187  = clock[10:0] < 10'h267;
  assign \$189  = \$185  & \$187 ;
  assign \$191  = clock[10:0] >= 10'h24e;
  assign \$193  = \$189  & \$191 ;
  assign \$195  = clock[10:0] >= 10'h280;
  assign \$197  = clock[21:11] >= 9'h1e0;
  assign \$19  = clock[21:11] < 9'h1ec;
  assign \$199  = \$195  | \$197 ;
  always @(posedge pix_clk)
    clock <= \clock$next ;
  assign \$21  = \$17  & \$19 ;
  assign \$23  = clock[10:0] - i_pope_location[9:0];
  assign \$25  = clock[21:11] - i_pope_location[19:10];
  assign \$27  = clock[21:11] - i_pope_location[19:10];
  assign \$2  = clock[10:0] + 1'h1;
  assign \$29  = clock[21:11] - i_pope_location[19:10];
  assign \$31  = clock[21:11] - i_pope_location[19:10];
  assign \$33  = clock[21:11] - i_pope_location[19:10];
  assign \$35  = clock[21:11] - i_pope_location[19:10];
  assign \$37  = clock[21:11] - i_pope_location[19:10];
  assign \$39  = clock[21:11] - i_pope_location[19:10];
  assign \$41  = clock[21:11] - i_pope_location[19:10];
  assign \$43  = clock[21:11] - i_pope_location[19:10];
  assign \$45  = clock[21:11] - i_pope_location[19:10];
  assign \$47  = clock[21:11] - i_pope_location[19:10];
  assign \$4  = clock[10:0] == 10'h31f;
  assign \$49  = clock[21:11] - i_pope_location[19:10];
  assign \$51  = clock[21:11] - i_pope_location[19:10];
  assign \$53  = clock[21:11] - i_pope_location[19:10];
  assign \$55  = clock[21:11] - i_pope_location[19:10];
  assign \$57  = clock[21:11] - i_pope_location[19:10];
  assign \$59  = clock[21:11] - i_pope_location[19:10];
  assign \$61  = clock[21:11] - i_pope_location[19:10];
  assign \$63  = clock[21:11] - i_pope_location[19:10];
  assign \$65  = clock[21:11] - i_pope_location[19:10];
  assign \$67  = clock[21:11] - i_pope_location[19:10];
  assign \$69  = clock[21:11] - i_pope_location[19:10];
  assign \$71  = clock[21:11] - i_pope_location[19:10];
  assign \$73  = clock[21:11] - i_pope_location[19:10];
  assign \$75  = clock[21:11] - i_pope_location[19:10];
  assign \$77  = clock[21:11] - i_pope_location[19:10];
  assign \$7  = clock[21:11] + 1'h1;
  assign \$79  = clock[21:11] - i_pope_location[19:10];
  assign \$81  = clock[21:11] - i_pope_location[19:10];
  assign \$83  = clock[21:11] - i_pope_location[19:10];
  assign \$85  = clock[21:11] - i_pope_location[19:10];
  assign \$87  = clock[21:11] >= i_paddle_location;
  assign \$89  = i_paddle_location + 8'h96;
  assign \$91  = clock[21:11] < \$89 ;
  assign \$93  = \$87  & \$91 ;
  assign \$95  = clock[10:0] >= 5'h19;
  assign \$97  = \$93  & \$95 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \clock$next  = clock;
    if (i_enable) begin
      \clock$next [10:0] = \$2 [10:0];
    end
    if (\$4 ) begin
      \clock$next [10:0] = 11'h000;
      \clock$next [21:11] = \$7 [10:0];
      if (\$9 ) begin
        \clock$next [21:11] = 11'h000;
      end
    end
    if (pix_rst) begin
      \clock$next  = 22'h000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_hsync = 1'h1;
    if (\$15 ) begin
      o_hsync = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_vsync = 1'h1;
    if (\$21 ) begin
      o_vsync = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    palette_index = 5'h00;
    casez (\$23 )
      12'h002:
          casez (\$25 )
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h15;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h15;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h18;
            12'h017:
                palette_index = 5'h13;
            12'h018:
                palette_index = 5'h1a;
          endcase
      12'h003:
          casez (\$27 )
            12'h00f:
                palette_index = 5'h0e;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h15;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h15;
            12'h016:
                palette_index = 5'h13;
            12'h017:
                palette_index = 5'h18;
            12'h018:
                palette_index = 5'h13;
            12'h019:
                palette_index = 5'h1e;
          endcase
      12'h004:
          casez (\$29 )
            12'h00c:
                palette_index = 5'h0e;
            12'h00d:
                palette_index = 5'h0d;
            12'h00e:
                palette_index = 5'h0b;
            12'h00f:
                palette_index = 5'h07;
            12'h010:
                palette_index = 5'h0e;
            12'h011:
                palette_index = 5'h0e;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h0c;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h12;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h17;
            12'h019:
                palette_index = 5'h18;
          endcase
      12'h005:
          casez (\$31 )
            12'h00c:
                palette_index = 5'h07;
            12'h00d:
                palette_index = 5'h07;
            12'h00e:
                palette_index = 5'h07;
            12'h00f:
                palette_index = 5'h0b;
            12'h010:
                palette_index = 5'h0b;
            12'h011:
                palette_index = 5'h0e;
            12'h012:
                palette_index = 5'h0c;
            12'h013:
                palette_index = 5'h0c;
            12'h014:
                palette_index = 5'h09;
            12'h015:
                palette_index = 5'h0a;
            12'h016:
                palette_index = 5'h0a;
            12'h017:
                palette_index = 5'h0a;
            12'h018:
                palette_index = 5'h09;
            12'h019:
                palette_index = 5'h0a;
            12'h01a:
                palette_index = 5'h09;
            12'h01b:
                palette_index = 5'h10;
            12'h01c:
                palette_index = 5'h09;
            12'h01d:
                palette_index = 5'h09;
            12'h01e:
                palette_index = 5'h05;
            12'h01f:
                palette_index = 5'h06;
            12'h020:
                palette_index = 5'h05;
            12'h021:
                palette_index = 5'h0c;
          endcase
      12'h006:
          casez (\$33 )
            12'h00c:
                palette_index = 5'h0b;
            12'h00d:
                palette_index = 5'h07;
            12'h00e:
                palette_index = 5'h0c;
            12'h00f:
                palette_index = 5'h0c;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h0c;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h09;
            12'h014:
                palette_index = 5'h0a;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h0a;
            12'h017:
                palette_index = 5'h09;
            12'h018:
                palette_index = 5'h0a;
            12'h019:
                palette_index = 5'h09;
            12'h01a:
                palette_index = 5'h0a;
            12'h01b:
                palette_index = 5'h09;
            12'h01c:
                palette_index = 5'h0a;
            12'h01d:
                palette_index = 5'h09;
            12'h01e:
                palette_index = 5'h0a;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h0a;
            12'h021:
                palette_index = 5'h09;
            12'h022:
                palette_index = 5'h10;
          endcase
      12'h007:
          casez (\$35 )
            12'h00c:
                palette_index = 5'h0c;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h0c;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h0c;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h0c;
            12'h013:
                palette_index = 5'h0f;
            12'h014:
                palette_index = 5'h0c;
            12'h015:
                palette_index = 5'h0f;
            12'h016:
                palette_index = 5'h0a;
            12'h017:
                palette_index = 5'h0f;
            12'h018:
                palette_index = 5'h0a;
            12'h019:
                palette_index = 5'h0a;
            12'h01a:
                palette_index = 5'h09;
            12'h01b:
                palette_index = 5'h0a;
            12'h01c:
                palette_index = 5'h09;
            12'h01d:
                palette_index = 5'h0a;
            12'h01e:
                palette_index = 5'h09;
            12'h01f:
                palette_index = 5'h0a;
            12'h020:
                palette_index = 5'h09;
            12'h021:
                palette_index = 5'h0a;
            12'h022:
                palette_index = 5'h09;
            12'h023:
                palette_index = 5'h15;
          endcase
      12'h008:
          casez (\$37 )
            12'h00c:
                palette_index = 5'h12;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h10;
            12'h00f:
                palette_index = 5'h0c;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h0c;
            12'h012:
                palette_index = 5'h12;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h12;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h12;
            12'h017:
                palette_index = 5'h0f;
            12'h018:
                palette_index = 5'h12;
            12'h019:
                palette_index = 5'h0a;
            12'h01a:
                palette_index = 5'h0a;
            12'h01b:
                palette_index = 5'h09;
            12'h01c:
                palette_index = 5'h0a;
            12'h01d:
                palette_index = 5'h09;
            12'h01e:
                palette_index = 5'h0a;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h0c;
            12'h021:
                palette_index = 5'h09;
            12'h022:
                palette_index = 5'h0c;
            12'h023:
                palette_index = 5'h09;
            12'h024:
                palette_index = 5'h1a;
          endcase
      12'h009:
          casez (\$39 )
            12'h00c:
                palette_index = 5'h10;
            12'h00d:
                palette_index = 5'h12;
            12'h00e:
                palette_index = 5'h10;
            12'h00f:
                palette_index = 5'h12;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h12;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h12;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h17;
            12'h016:
                palette_index = 5'h12;
            12'h017:
                palette_index = 5'h17;
            12'h018:
                palette_index = 5'h12;
            12'h019:
                palette_index = 5'h17;
            12'h01a:
                palette_index = 5'h0a;
            12'h01b:
                palette_index = 5'h0f;
            12'h01c:
                palette_index = 5'h09;
            12'h01d:
                palette_index = 5'h0a;
            12'h01e:
                palette_index = 5'h09;
            12'h01f:
                palette_index = 5'h0c;
            12'h020:
                palette_index = 5'h09;
            12'h021:
                palette_index = 5'h0c;
            12'h022:
                palette_index = 5'h09;
            12'h023:
                palette_index = 5'h0c;
            12'h024:
                palette_index = 5'h09;
          endcase
      12'h00a:
          casez (\$41 )
            12'h00c:
                palette_index = 5'h12;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h12;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h12;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h12;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h12;
            12'h015:
                palette_index = 5'h12;
            12'h016:
                palette_index = 5'h18;
            12'h017:
                palette_index = 5'h18;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h12;
            12'h01a:
                palette_index = 5'h17;
            12'h01b:
                palette_index = 5'h0f;
            12'h01c:
                palette_index = 5'h0f;
            12'h01d:
                palette_index = 5'h0a;
            12'h01e:
                palette_index = 5'h0f;
            12'h01f:
                palette_index = 5'h0c;
            12'h020:
                palette_index = 5'h0f;
            12'h021:
                palette_index = 5'h0c;
            12'h022:
                palette_index = 5'h0c;
            12'h023:
                palette_index = 5'h09;
            12'h024:
                palette_index = 5'h0c;
          endcase
      12'h00b:
          casez (\$43 )
            12'h00c:
                palette_index = 5'h10;
            12'h00d:
                palette_index = 5'h12;
            12'h00e:
                palette_index = 5'h10;
            12'h00f:
                palette_index = 5'h12;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h12;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h12;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h17;
            12'h016:
                palette_index = 5'h18;
            12'h017:
                palette_index = 5'h1a;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h17;
            12'h01c:
                palette_index = 5'h0f;
            12'h01d:
                palette_index = 5'h0f;
            12'h01e:
                palette_index = 5'h0c;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h0c;
            12'h023:
                palette_index = 5'h0c;
            12'h024:
                palette_index = 5'h09;
          endcase
      12'h00c:
          casez (\$45 )
            12'h00c:
                palette_index = 5'h12;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h12;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h12;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h12;
            12'h013:
                palette_index = 5'h0c;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h1a;
            12'h017:
                palette_index = 5'h18;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h12;
            12'h01c:
                palette_index = 5'h12;
            12'h01d:
                palette_index = 5'h0a;
            12'h01e:
                palette_index = 5'h0f;
            12'h01f:
                palette_index = 5'h0f;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h0c;
            12'h024:
                palette_index = 5'h0c;
          endcase
      12'h00d:
          casez (\$47 )
            12'h00c:
                palette_index = 5'h10;
            12'h00d:
                palette_index = 5'h12;
            12'h00e:
                palette_index = 5'h10;
            12'h00f:
                palette_index = 5'h12;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h12;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h09;
            12'h014:
                palette_index = 5'h05;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h13;
            12'h017:
                palette_index = 5'h1a;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h17;
            12'h01c:
                palette_index = 5'h0f;
            12'h01d:
                palette_index = 5'h0f;
            12'h01e:
                palette_index = 5'h09;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h10;
          endcase
      12'h00e:
          casez (\$49 )
            12'h00c:
                palette_index = 5'h15;
            12'h00d:
                palette_index = 5'h10;
            12'h00e:
                palette_index = 5'h12;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h12;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h12;
            12'h013:
                palette_index = 5'h05;
            12'h014:
                palette_index = 5'h04;
            12'h015:
                palette_index = 5'h05;
            12'h016:
                palette_index = 5'h15;
            12'h017:
                palette_index = 5'h17;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h12;
            12'h01c:
                palette_index = 5'h12;
            12'h01d:
                palette_index = 5'h09;
            12'h01e:
                palette_index = 5'h12;
            12'h01f:
                palette_index = 5'h10;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h12;
          endcase
      12'h00f:
          casez (\$51 )
            12'h00c:
                palette_index = 5'h13;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h13;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h06;
            12'h014:
                palette_index = 5'h02;
            12'h015:
                palette_index = 5'h04;
            12'h016:
                palette_index = 5'h09;
            12'h017:
                palette_index = 5'h12;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h17;
            12'h01c:
                palette_index = 5'h0a;
            12'h01d:
                palette_index = 5'h12;
            12'h01e:
                palette_index = 5'h10;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h17;
            12'h024:
                palette_index = 5'h12;
          endcase
      12'h010:
          casez (\$53 )
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h15;
            12'h013:
                palette_index = 5'h05;
            12'h014:
                palette_index = 5'h04;
            12'h015:
                palette_index = 5'h02;
            12'h016:
                palette_index = 5'h09;
            12'h017:
                palette_index = 5'h0c;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h0f;
            12'h01c:
                palette_index = 5'h12;
            12'h01d:
                palette_index = 5'h12;
            12'h01e:
                palette_index = 5'h18;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h17;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h17;
          endcase
      12'h011:
          casez (\$55 )
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h09;
            12'h014:
                palette_index = 5'h02;
            12'h015:
                palette_index = 5'h03;
            12'h016:
                palette_index = 5'h04;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h12;
            12'h01b:
                palette_index = 5'h12;
            12'h01c:
                palette_index = 5'h12;
            12'h01d:
                palette_index = 5'h17;
            12'h01e:
                palette_index = 5'h17;
            12'h01f:
                palette_index = 5'h17;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h17;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h17;
            12'h024:
                palette_index = 5'h12;
          endcase
      12'h012:
          casez (\$57 )
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h05;
            12'h015:
                palette_index = 5'h02;
            12'h016:
                palette_index = 5'h06;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h13;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h12;
            12'h01c:
                palette_index = 5'h17;
            12'h01d:
                palette_index = 5'h10;
            12'h01e:
                palette_index = 5'h17;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h17;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h17;
          endcase
      12'h013:
          casez (\$59 )
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h05;
            12'h015:
                palette_index = 5'h06;
            12'h016:
                palette_index = 5'h09;
            12'h017:
                palette_index = 5'h17;
            12'h018:
                palette_index = 5'h17;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h17;
            12'h01b:
                palette_index = 5'h17;
            12'h01c:
                palette_index = 5'h17;
            12'h01d:
                palette_index = 5'h12;
            12'h01e:
                palette_index = 5'h10;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h12;
          endcase
      12'h014:
          casez (\$61 )
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h13;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h12;
            12'h017:
                palette_index = 5'h17;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h13;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h1a;
            12'h01d:
                palette_index = 5'h17;
            12'h01e:
                palette_index = 5'h12;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h12;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h10;
            12'h024:
                palette_index = 5'h17;
          endcase
      12'h015:
          casez (\$63 )
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h1a;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h12;
            12'h016:
                palette_index = 5'h10;
            12'h017:
                palette_index = 5'h1a;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h1a;
            12'h01c:
                palette_index = 5'h1a;
            12'h01d:
                palette_index = 5'h1a;
            12'h01e:
                palette_index = 5'h10;
            12'h01f:
                palette_index = 5'h0c;
            12'h020:
                palette_index = 5'h0c;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h12;
          endcase
      12'h016:
          casez (\$65 )
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h0c;
            12'h016:
                palette_index = 5'h0c;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h1a;
            12'h01d:
                palette_index = 5'h13;
            12'h01e:
                palette_index = 5'h12;
            12'h01f:
                palette_index = 5'h0c;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h10;
            12'h024:
                palette_index = 5'h17;
          endcase
      12'h017:
          casez (\$67 )
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h1a;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h02;
            12'h017:
                palette_index = 5'h05;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h10;
            12'h01d:
                palette_index = 5'h10;
            12'h01e:
                palette_index = 5'h0c;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h0c;
            12'h021:
                palette_index = 5'h12;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h12;
          endcase
      12'h018:
          casez (\$69 )
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h12;
            12'h015:
                palette_index = 5'h04;
            12'h016:
                palette_index = 5'h01;
            12'h017:
                palette_index = 5'h01;
            12'h018:
                palette_index = 5'h10;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h10;
            12'h01d:
                palette_index = 5'h06;
            12'h01e:
                palette_index = 5'h06;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h09;
            12'h021:
                palette_index = 5'h0c;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h10;
            12'h024:
                palette_index = 5'h12;
          endcase
      12'h019:
          casez (\$71 )
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h1a;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h04;
            12'h016:
                palette_index = 5'h02;
            12'h017:
                palette_index = 5'h03;
            12'h018:
                palette_index = 5'h10;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h1a;
            12'h01c:
                palette_index = 5'h13;
            12'h01d:
                palette_index = 5'h0c;
            12'h01e:
                palette_index = 5'h05;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h09;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h10;
            12'h023:
                palette_index = 5'h12;
            12'h024:
                palette_index = 5'h10;
          endcase
      12'h01a:
          casez (\$73 )
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h04;
            12'h016:
                palette_index = 5'h01;
            12'h017:
                palette_index = 5'h01;
            12'h018:
                palette_index = 5'h15;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h1a;
            12'h01c:
                palette_index = 5'h1a;
            12'h01d:
                palette_index = 5'h10;
            12'h01e:
                palette_index = 5'h0a;
            12'h01f:
                palette_index = 5'h09;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h10;
            12'h022:
                palette_index = 5'h12;
            12'h023:
                palette_index = 5'h1a;
          endcase
      12'h01b:
          casez (\$75 )
            12'h00c:
                palette_index = 5'h1b;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h1a;
            12'h010:
                palette_index = 5'h18;
            12'h011:
                palette_index = 5'h1a;
            12'h012:
                palette_index = 5'h18;
            12'h013:
                palette_index = 5'h1a;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h01;
            12'h017:
                palette_index = 5'h04;
            12'h018:
                palette_index = 5'h15;
            12'h019:
                palette_index = 5'h1a;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h1a;
            12'h01c:
                palette_index = 5'h18;
            12'h01d:
                palette_index = 5'h12;
            12'h01e:
                palette_index = 5'h0a;
            12'h01f:
                palette_index = 5'h12;
            12'h020:
                palette_index = 5'h10;
            12'h021:
                palette_index = 5'h1a;
            12'h022:
                palette_index = 5'h1e;
          endcase
      12'h01c:
          casez (\$77 )
            12'h00c:
                palette_index = 5'h1e;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h1a;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h1a;
            12'h011:
                palette_index = 5'h18;
            12'h012:
                palette_index = 5'h1a;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h18;
            12'h015:
                palette_index = 5'h09;
            12'h016:
                palette_index = 5'h05;
            12'h017:
                palette_index = 5'h05;
            12'h018:
                palette_index = 5'h18;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h1a;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h18;
            12'h01d:
                palette_index = 5'h10;
            12'h01e:
                palette_index = 5'h12;
            12'h01f:
                palette_index = 5'h15;
            12'h020:
                palette_index = 5'h1f;
          endcase
      12'h01d:
          casez (\$79 )
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h1a;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h18;
            12'h010:
                palette_index = 5'h15;
            12'h011:
                palette_index = 5'h15;
            12'h012:
                palette_index = 5'h15;
            12'h013:
                palette_index = 5'h18;
            12'h014:
                palette_index = 5'h10;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h09;
            12'h017:
                palette_index = 5'h10;
            12'h018:
                palette_index = 5'h13;
            12'h019:
                palette_index = 5'h18;
            12'h01a:
                palette_index = 5'h13;
            12'h01b:
                palette_index = 5'h18;
            12'h01c:
                palette_index = 5'h18;
            12'h01d:
                palette_index = 5'h1e;
          endcase
      12'h01e:
          casez (\$81 )
            12'h00c:
                palette_index = 5'h1a;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h18;
            12'h00f:
                palette_index = 5'h15;
            12'h010:
                palette_index = 5'h15;
            12'h011:
                palette_index = 5'h10;
            12'h012:
                palette_index = 5'h15;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h15;
            12'h015:
                palette_index = 5'h0c;
            12'h016:
                palette_index = 5'h0c;
            12'h017:
                palette_index = 5'h0c;
            12'h018:
                palette_index = 5'h15;
            12'h019:
                palette_index = 5'h10;
            12'h01a:
                palette_index = 5'h18;
            12'h01b:
                palette_index = 5'h1b;
          endcase
      12'h01f:
          casez (\$83 )
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h18;
            12'h00e:
                palette_index = 5'h15;
            12'h00f:
                palette_index = 5'h15;
            12'h010:
                palette_index = 5'h10;
            12'h011:
                palette_index = 5'h15;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h10;
            12'h014:
                palette_index = 5'h0c;
            12'h015:
                palette_index = 5'h10;
            12'h016:
                palette_index = 5'h0c;
            12'h017:
                palette_index = 5'h15;
            12'h018:
                palette_index = 5'h1a;
            12'h019:
                palette_index = 5'h1e;
          endcase
      12'h020:
          casez (\$85 )
            12'h00c:
                palette_index = 5'h18;
            12'h00d:
                palette_index = 5'h13;
            12'h00e:
                palette_index = 5'h15;
            12'h00f:
                palette_index = 5'h10;
            12'h010:
                palette_index = 5'h15;
            12'h011:
                palette_index = 5'h0e;
            12'h012:
                palette_index = 5'h10;
            12'h013:
                palette_index = 5'h0e;
            12'h014:
                palette_index = 5'h1b;
            12'h015:
                palette_index = 5'h1b;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_r = 3'h0;
    casez (palette_index)
      5'h01:
          o_r = 3'h2;
      5'h02:
          o_r = 3'h3;
      5'h03:
          o_r = 3'h2;
      5'h04:
          o_r = 3'h3;
      5'h05:
          o_r = 3'h4;
      5'h06:
          o_r = 3'h4;
      5'h07:
          o_r = 3'h4;
      5'h08:
          o_r = 3'h4;
      5'h09:
          o_r = 3'h5;
      5'h0a:
          o_r = 3'h6;
      5'h0b:
          o_r = 3'h4;
      5'h0c:
          o_r = 3'h5;
      5'h0d:
          o_r = 3'h4;
      5'h0e:
          o_r = 3'h5;
      5'h0f:
          o_r = 3'h6;
      5'h10:
          o_r = 3'h6;
      5'h11:
          o_r = 3'h6;
      5'h12:
          o_r = 3'h7;
      5'h13:
          o_r = 3'h7;
      5'h14:
          o_r = 3'h5;
      5'h15:
          o_r = 3'h6;
      5'h16:
          o_r = 3'h6;
      5'h17:
          o_r = 3'h7;
      5'h18:
          o_r = 3'h7;
      5'h19:
          o_r = 3'h7;
      5'h1a:
          o_r = 3'h7;
      5'h1b:
          o_r = 3'h7;
      5'h1c:
          o_r = 3'h5;
      5'h1d:
          o_r = 3'h7;
      5'h1e:
          o_r = 3'h7;
    endcase
    if (\$101 ) begin
      o_r = 3'h7;
    end
    if (\$117 ) begin
      o_r = 3'h7;
    end
    if (\$123 ) begin
      o_r = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_g = 3'h0;
    casez (palette_index)
      5'h01:
          o_g = 3'h1;
      5'h02:
          o_g = 3'h0;
      5'h03:
          o_g = 3'h2;
      5'h04:
          o_g = 3'h2;
      5'h05:
          o_g = 3'h2;
      5'h06:
          o_g = 3'h3;
      5'h07:
          o_g = 3'h3;
      5'h08:
          o_g = 3'h3;
      5'h09:
          o_g = 3'h3;
      5'h0a:
          o_g = 3'h3;
      5'h0b:
          o_g = 3'h4;
      5'h0c:
          o_g = 3'h4;
      5'h0d:
          o_g = 3'h4;
      5'h0e:
          o_g = 3'h4;
      5'h0f:
          o_g = 3'h4;
      5'h10:
          o_g = 3'h4;
      5'h11:
          o_g = 3'h4;
      5'h12:
          o_g = 3'h4;
      5'h13:
          o_g = 3'h4;
      5'h14:
          o_g = 3'h5;
      5'h15:
          o_g = 3'h5;
      5'h16:
          o_g = 3'h5;
      5'h17:
          o_g = 3'h5;
      5'h18:
          o_g = 3'h5;
      5'h19:
          o_g = 3'h5;
      5'h1a:
          o_g = 3'h6;
      5'h1b:
          o_g = 3'h6;
      5'h1c:
          o_g = 3'h6;
      5'h1d:
          o_g = 3'h6;
      5'h1e:
          o_g = 3'h7;
    endcase
    if (\$139 ) begin
      o_g = 3'h7;
    end
    if (\$155 ) begin
      o_g = 3'h7;
    end
    if (\$161 ) begin
      o_g = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    o_b = 3'h0;
    casez (palette_index)
      5'h01:
          o_b = 3'h0;
      5'h02:
          o_b = 3'h0;
      5'h03:
          o_b = 3'h0;
      5'h04:
          o_b = 3'h1;
      5'h05:
          o_b = 3'h0;
      5'h06:
          o_b = 3'h0;
      5'h07:
          o_b = 3'h2;
      5'h08:
          o_b = 3'h3;
      5'h09:
          o_b = 3'h0;
      5'h0a:
          o_b = 3'h0;
      5'h0b:
          o_b = 3'h1;
      5'h0c:
          o_b = 3'h1;
      5'h0d:
          o_b = 3'h4;
      5'h0e:
          o_b = 3'h3;
      5'h0f:
          o_b = 3'h0;
      5'h10:
          o_b = 3'h2;
      5'h11:
          o_b = 3'h4;
      5'h12:
          o_b = 3'h1;
      5'h13:
          o_b = 3'h3;
      5'h14:
          o_b = 3'h3;
      5'h15:
          o_b = 3'h2;
      5'h16:
          o_b = 3'h4;
      5'h17:
          o_b = 3'h1;
      5'h18:
          o_b = 3'h3;
      5'h19:
          o_b = 3'h5;
      5'h1a:
          o_b = 3'h3;
      5'h1b:
          o_b = 3'h5;
      5'h1c:
          o_b = 3'h5;
      5'h1d:
          o_b = 3'h7;
      5'h1e:
          o_b = 3'h5;
    endcase
    if (\$177 ) begin
      o_b = 3'h7;
    end
    if (\$193 ) begin
      o_b = 3'h7;
    end
    if (\$199 ) begin
      o_b = 3'h0;
    end
  end
  assign \$1  = \$2 ;
  assign \$6  = \$7 ;
endmodule
